import LegalPage, { LegalSection } from "@/components/LegalPage";

const sections: LegalSection[] = [
    { id: "controller", title: "Veri sorumlusu ve temsilci", paragraphs: ["6698 sayılı Kanun kapsamında veri sorumlusu, Hanogt Codev hizmetini işleten HanStudios/Hanogt Codev işletmesidir. Kesin ticari unvan, MERSİS/VKN, açık adres, KEP ve irtibat e-postası üretim öncesinde bu metne eklenmelidir. Eksik kimlik bilgisiyle ticari yayına geçilmemelidir."] },
    { id: "methods", title: "Toplama yöntemleri", items: ["Kayıt, profil, proje, mesajlaşma ve geri bildirim formları üzerinden otomatik yollarla.", "Google OAuth seçildiğinde yetkilendirme sağlayıcısından.", "Tarayıcı, uygulama, güvenlik günlükleri ve hız-sınırı kayıtlarından otomatik yollarla.", "WebRTC sesli arama sırasında geçici sinyalleşme ve ağ bağlantısı verilerinden."] },
    { id: "categories", title: "Veri, amaç ve hukuki sebep matrisi", items: ["E-posta/kullanıcı adı → hesap ve iletişim → sözleşmenin kurulması veya ifası.", "Parola karması/oturum → kimlik doğrulama → sözleşme ve meşru menfaat.", "Kod proje dosyaları ile oyun sahnesi/nesne/bileşen ve C#/C++ script kaynakları → editör, oyun motoru ve bulut saklama → sözleşmenin ifası.", "Arkadaşlık/mesaj/sesli mesaj → sosyal özellik → sözleşmenin ifası ve kullanıcı tercihi.", "IP türevi anahtar/güvenlik olayı → kötüye kullanım önleme → meşru menfaat ve hukuki yükümlülük.", "İsteğe bağlı profil ve sosyal bağlantılar → profil sunumu → kullanıcı tercihi; gerektiğinde açık rıza."] },
    { id: "community-data", title: "Media, grup ve ortak çalışma verileri", items: ["Media proje anlık görüntüsü → kullanıcının açık yayınlama talebi → sözleşmenin ifası ve içeriği alenileştirme iradesi.", "Media profil adı/avatarı → kullanıcı görünürlük tercihi → hizmetin ifası; zorunlu olmayan görünürlük için tercih yönetimi.", "Beğeni, yorum ve rapor → topluluk etkileşimi, sayım ve moderasyon → sözleşmenin ifası ve meşru menfaat.", "Grup üyeliği ve üye e-postası → özel çalışma alanına erişim ve yetkilendirme → sözleşmenin ifası.", "Ortak dosya, değişiklik yapan üye ve grup sohbeti → iş birliği/senkronizasyon → sözleşmenin ifası.", "Security Bot için ayrıca işaretlenen proje → güvenlik geliştirme araştırması → geri alınabilir açık rıza."] },
    { id: "transfers", title: "Aktarım amaçları ve alıcı grupları", paragraphs: ["Veriler; barındırma/veritabanı/depolama hizmeti, seçilen kimlik sağlayıcısı, kullanıcının özellikle çağırdığı yapay zekâ aracı, izole kod çalıştırma altyapısı ve WebRTC bağlantı hizmeti sağlayıcılarına amaçla sınırlı aktarılabilir. Kamu kurumlarına yalnızca hukuka uygun ve bağlayıcı talep kapsamında aktarım yapılır.", "Yurt dışı aktarım söz konusuysa KVKK m.9 uyarınca yeterlilik kararı, uygun güvence veya kanundaki istisnai hâllerden uygun olanı belgelenir. Sadece genel bir gizlilik politikası onayı, gerekli olduğu durumda ayrı açık rızanın yerine geçmez."] },
    { id: "rights", title: "İlgili kişinin hakları", items: ["İşlenme durumunu ve amacı öğrenme; alıcıları bilme.", "Düzeltme, silme/yok etme ve aktarılanlara bildirim isteme.", "Otomatik analiz sonucuna itiraz etme ve zarar varsa giderim talep etme.", "Hesap ayarlarından veri kopyası indirme ve uygun olduğunda taşınabilir format talep etme."] },
    { id: "application", title: "Başvuru kanalı ve yanıt", paragraphs: ["Kimliği doğrulanmış kullanıcı, Geri Bildirim ve SSS sayfasındaki “Gizlilik/KVKK” kategorisinden başvurabilir. Kanunda ve Veri Sorumlusuna Başvuru Tebliği’nde belirtilen diğer yazılı/elektronik yöntemler, kesin KEP ve adres bilgileri yayımlandığında ayrıca listelenir.", "Başvuru mümkün olan en kısa sürede ve en geç 30 gün içinde sonuçlandırılır. Kimlik doğrulamak için yalnızca gerekli ek bilgi istenir; başvuru içeriği üçüncü kişilerle paylaşılmaz."] },
    { id: "consent", title: "Aydınlatma ile açık rıza ayrımı", paragraphs: ["Bu aydınlatma metninin okunması veya onaylanması, açık rıza gerektiren tüm işlemlere toplu rıza anlamına gelmez. Pazarlama, hassas veri veya kanunda ayrıca rıza gerektiren işlem varsa amaç bazlı, ayrı ve geri alınabilir tercih sunulur. Hizmetin zorunlu olmayan özelliği için verilen rıza geri çekildiğinde temel hesap işlevleri mümkün olduğu ölçüde devam eder."] },
    { id: "security-consent", title: "Security katkı tercihinin kapsamı", paragraphs: ["Güvenlik katkı tercihi iki aşamalıdır: hesap düzeyindeki program tercihi ve proje düzeyindeki dahil etme kutusu. Her ikisi de etkin değilse proje güvenlik geliştirme veri setine aday gösterilmez. Rıza; Media sayfasından ileriye etkili biçimde geri çekilebilir, bekleyen aday kayıtlar silinir ve temel hizmet etkilenmez.", "Üretimde gerçek bir model eğitimi veya üçüncü tarafa veri seti aktarımı başlatılacaksa; alıcı, ülke, saklama süresi, anonimleştirme yöntemi, modelden silme sınırları ve ilgili kişi hakları işlem başlamadan önce ayrı metinde açıklanır ve gereken aktarım mekanizması kurulur."] },
    { id: "retention-table", title: "Saklama yaklaşımı ve imha", items: ["Hesap/kod projesi/oyun projesi/grup: hesap veya üyelik sürdükçe; silme talebinde sahne ve script alt kayıtları dâhil yasal istisnalar dışında imha sürecine alınır.", "WebRTC sinyalleşme: normal kapanışta silinir; beklenmeyen kopmada iki dakikalık son kullanım işareti sonrasında TTL sürecine girer.", "Sesli mesaj: kullanıcı mesajı sildiğinde depolama nesnesiyle birlikte silinir; grup sahibi grubu sildiğinde grup ses dosyaları da silinir.", "Hız sınırı: güvenlik penceresi sona erdiğinde TTL; güvenlik/rapor kayıtları ise olay incelemesi ve zamanaşımı ihtiyacına göre ölçülü süre.", "Kesin üretim süreleri saklama ve imha politikasında veri kategorisi bazında belirlenir; süre dolunca silme, yok etme veya anonimleştirme uygulanır."] },
];

export default function DisclosurePage() {
    return <LegalPage eyebrow="KVKK m.10" title="Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni" summary="Veri sorumlusunun kimliği, işleme amaçları, hukuki sebepler, aktarım alıcıları, toplama yöntemi ve başvuru hakları hakkında katmanlı bilgilendirme." sections={sections} notice="Aydınlatma yükümlülüğü, veri elde edilirken yerine getirilmelidir. Bu sayfa kayıt ekranındaki kısa bilgilendirme ve amaç bazlı tercihlerle birlikte kullanılmalıdır." />;
}
