import type { Copy } from "@/lib/i18n";
import type { CouponRecur, PlanId } from "@/lib/plans";

/** The words of the Pricing page (src/app/plans/page.tsx and the components next to this file). */
export const C = {
    badge: { TR: "Yakında", EN: "Coming soon" },
    badgeOpen: { TR: "Planlar açıldı", EN: "Plans are open" },
    title: { TR: "Hanogt Codev Planları", EN: "Hanogt Codev Plans" },
    subtitle: { TR: "Hanogt Codev ücretsiz kalacak. Daha fazlasını isteyenler için Plus ve Pro hazırlanıyor; şu anda ödeme alınmıyor ve hiçbir kart bilgisi istenmiyor.", EN: "Hanogt Codev stays free. Plus and Pro are being prepared for people who want more; no payments are taken right now and no card details are asked for." },
    subtitleOpen: { TR: "Hanogt Codev ücretsiz kalacak. Daha çok Hanogt AI ve destekte öncelik isteyenler için Plus ve Pro. Ödemeler Paddle üzerinden güvenle alınır; kart bilgilerin bize ulaşmaz.", EN: "Hanogt Codev stays free. Plus and Pro are for people who want more Hanogt AI and priority support. Payments are handled securely by Paddle; your card details never reach us." },
    subtitleSubscriber: { TR: "Aboneliğin Paddle üzerinden yönetilir. Yeni satışlar şu anda kapalı; mevcut aboneliğin bundan etkilenmez.", EN: "Your subscription is managed through Paddle. New sales are closed right now; your subscription isn't affected." },
    yourPlan: { TR: "Planın: {plan}", EN: "Your plan: {plan}" },
    assigned: { TR: "Hanogt ekibi tarafından tanımlandı", EN: "Assigned by the Hanogt team" },
    paidMonthly: { TR: "Aylık abonelik", EN: "Monthly subscription" },
    paidYearly: { TR: "Yıllık abonelik", EN: "Yearly subscription" },
    paidOther: { TR: "Abonelik", EN: "Subscription" },
    until: { TR: "{date} tarihine kadar", EN: "until {date}" },
    renews: { TR: "Sonraki ödeme: {date}", EN: "Next payment: {date}" },
    endsAt: { TR: "Aboneliğin {date} tarihinde sona erecek; avantajların o güne kadar sürer.", EN: "Your subscription ends on {date}; your benefits last until then." },
    keep: { TR: "Vazgeç, aboneliğim devam etsin", EN: "Undo, keep my subscription" },
    pastDue: { TR: "Son ödemen alınamadı. Paddle ödemeyi birkaç kez daha deneyecek; avantajların bu sürede devam eder.", EN: "Your last payment didn't go through. Paddle will try again a few times; your benefits continue meanwhile." },
    updatePayment: { TR: "Ödeme yöntemini güncelle", EN: "Update payment method" },
    paused: { TR: "Aboneliğin duraklatıldı; avantajların sürdürünce geri gelir.", EN: "Your subscription is paused; your benefits come back when you resume it." },
    resume: { TR: "Aboneliği sürdür", EN: "Resume subscription" },
    resumeCharge: { TR: "Sürdürünce yeni ödeme dönemi bugün başlar ve Paddle {plan} planının ücretini kayıtlı ödeme yönteminden hemen alır.", EN: "When you resume, a new billing period starts today and Paddle charges the {plan} plan to your saved payment method right away." },
    resumeFree: { TR: "Ödediğin dönem {date} tarihine kadar sürüyor; şimdi sürdürürsen ücret alınmaz.", EN: "Your paid period runs until {date}; resuming now costs nothing." },
    resumeConfirm: { TR: "Onayla ve sürdür", EN: "Confirm and resume" },
    resumeCancel: { TR: "Vazgeç", EN: "Cancel" },
    resumed: { TR: "Aboneliğin sürdürüldü; {plan} planın yeniden etkin.", EN: "Your subscription is resumed; your {plan} plan is active again." },
    ended: { TR: "Önceki aboneliğin sona erdi.", EN: "Your previous subscription has ended." },
    manage: { TR: "Aboneliği yönet", EN: "Manage subscription" },
    manageHint: { TR: "Fatura, ödeme yöntemi ve iptal Paddle'ın güvenli müşteri portalında.", EN: "Invoices, payment method and cancellation are in Paddle's secure customer portal." },
    cancelSubscription: { TR: "Ücretsiz plana dönmek için aboneliği iptal et", EN: "Cancel your subscription to go back to Free" },
    blocked: { TR: "Plan avantajların şu anda kullanıma kapalı. Bir sorun olduğunu düşünüyorsan destek talebi aç.", EN: "Your plan benefits are switched off right now. If you think that's a mistake, open a support ticket." },
    aiWindow: { TR: "Hanogt AI ({days} gün): {used} / {limit} mesaj", EN: "Hanogt AI ({days} days): {used} / {limit} messages" },
    monthly: { TR: "Aylık", EN: "Monthly" },
    yearly: { TR: "Yıllık", EN: "Yearly" },
    save: { TR: "%{percent} tasarruf", EN: "Save {percent}%" },
    perMonth: { TR: "/ay", EN: "/month" },
    perYearShort: { TR: "/yıl", EN: "/year" },
    perYear: { TR: "Yıllık {price}", EN: "{price} per year" },
    monthlyEquivalent: { TR: "Aylık {price} karşılığı", EN: "{price} a month" },
    onlyInterval: { TR: "Bu plan şimdilik yalnızca {interval} ödemeyle satılıyor.", EN: "This plan is sold with {interval} billing only for now." },
    priceAtCheckout: { TR: "Fiyat ödeme ekranında gösterilir", EN: "The price is shown at checkout" },
    trial: { TR: "{days} gün ücretsiz dene", EN: "{days}-day free trial" },
    priceSoon: { TR: "Fiyat yakında açıklanacak", EN: "Price to be announced" },
    forever: { TR: "her zaman", EN: "forever" },
    current: { TR: "Şu anki planın", EN: "Your current plan" },
    startFree: { TR: "Ücretsiz başla", EN: "Start for free" },
    buyPlus: { TR: "Plus'a geç", EN: "Get Plus" },
    buyPro: { TR: "Pro'ya geç", EN: "Get Pro" },
    upgradePro: { TR: "Pro'ya yükselt", EN: "Upgrade to Pro" },
    switchPlus: { TR: "Plus'a geç", EN: "Switch to Plus" },
    switchYearly: { TR: "Yıllık ödemeye geç", EN: "Switch to yearly" },
    switchMonthly: { TR: "Aylık ödemeye geç", EN: "Switch to monthly" },
    ownSubscription: { TR: "Kendi aboneliğini başlat", EN: "Start your own subscription" },
    signInToBuy: { TR: "Giriş yap ve satın al", EN: "Sign in to buy" },
    payFirst: { TR: "Önce ödeme yöntemini güncelle", EN: "Update your payment method first" },
    unavailableBlocked: { TR: "Kullanıma kapalı", EN: "Not available" },
    notify: { TR: "Açılınca haber ver", EN: "Notify me when it opens" },
    notified: { TR: "Haber vereceğiz", EN: "We'll let you know" },
    notifyHint: { TR: "Bildirimden çıkmak için tekrar bas.", EN: "Press again to stop the notification." },
    signInToNotify: { TR: "Haber almak için giriş yap", EN: "Sign in to get notified" },
    planned: { TR: "Planlanıyor", EN: "Planned" },
    popular: { TR: "En kapsamlı", EN: "Most complete" },
    discount: { TR: "%{percent} indirim", EN: "{percent}% off" },
    activating: { TR: "Ödemen alındı, planın etkinleştiriliyor…", EN: "Payment received, activating your plan…" },
    welcome: { TR: "Hoş geldin! {plan} planın etkin.", EN: "Welcome! Your {plan} plan is active." },
    activationSlow: { TR: "Ödemen alındı; planın birkaç dakika içinde etkinleşecek. Hemen denemek için \"Ödememi kontrol et\"e bas.", EN: "Payment received; your plan will be active within a few minutes. To try right away, press \"Check my payment\"." },
    checkPayment: { TR: "Ödememi kontrol et", EN: "Check my payment" },
    checkPaymentHint: { TR: "Ödeme yaptın ama planın değişmedi mi?", EN: "Paid, but your plan didn't change?" },
    paymentNotFound: { TR: "Paddle'da bu hesaba ait tamamlanmış bir ödeme bulunamadı. Ödeme ekranını tamamladıysan birkaç dakika sonra tekrar dene; sürerse destek talebi oluştur.", EN: "Paddle has no completed payment for this account. If you finished the checkout, try again in a few minutes; if it persists, open a support ticket." },
    paymentPending: { TR: "Ödemen alındı, Paddle aboneliğini oluşturuyor. Planın birkaç saniye içinde açılacak; yeniden ödeme yapmana gerek yok.", EN: "Your payment went through and Paddle is creating your subscription. Your plan will be active in a few seconds; there's no need to pay again." },
    changed: { TR: "Planın değişti: {plan}.", EN: "Your plan changed: {plan}." },
    kept: { TR: "Aboneliğin devam ediyor.", EN: "Your subscription will continue." },
    failed: { TR: "İşlem tamamlanamadı. Biraz sonra tekrar dene.", EN: "That didn't work. Try again in a moment." },
    retrying: { TR: "İlk deneme olmadı, bir kez daha deneniyor…", EN: "The first try didn't work; trying once more…" },
    networkFailed: { TR: "Sunucuya ulaşılamadı. İnternet bağlantını kontrol et; reklam engelleyici, tarayıcı koruması ya da VPN kullanıyorsan bu site için kapatıp tekrar dene.", EN: "Couldn't reach the server. Check your connection; if you use an ad blocker, browser protection or a VPN, turn it off for this site and try again." },
    serverTimeout: { TR: "Sunucu zamanında yanıt vermedi; ödeme sağlayıcısı ya da veritabanı şu an yavaş. Biraz sonra tekrar dene.", EN: "The server didn't answer in time; the payment provider or the database is slow right now. Try again in a moment." },
    databaseFailed: { TR: "Hesap bilgilerine şu an ulaşılamıyor (veritabanı yanıt vermedi). Biraz sonra tekrar dene.", EN: "Your account details can't be reached right now (the database didn't answer). Try again in a moment." },
    reloadPage: { TR: "İstek bu sayfadan doğrulanamadı. Sayfayı yenileyip tekrar dene.", EN: "The request couldn't be verified from this page. Refresh the page and try again." },
    noSubscription: { TR: "Bu hesapta etkin bir abonelik bulunamadı. Sayfayı yenile.", EN: "No active subscription was found on this account. Refresh the page." },
    noChange: { TR: "Değiştirilecek bir şey yok; sayfayı yenile.", EN: "There's nothing to change; refresh the page." },
    reference: { TR: "Hata kodu: {ref}", EN: "Error code: {ref}" },
    couponQuestion: { TR: "Kupon kodun var mı?", EN: "Have a coupon code?" },
    couponLabel: { TR: "Kupon kodu", EN: "Coupon code" },
    couponApply: { TR: "Uygula", EN: "Apply" },
    couponSignIn: { TR: "Kupon kullanmak için giriş yap", EN: "Sign in to use a coupon" },
    couponSignInCode: { TR: "{code} kuponunu kullanmak için giriş yap", EN: "Sign in to use the coupon {code}" },
    couponSubscribed: { TR: "Kuponlar yeni aboneliklerde geçerlidir; mevcut aboneliğine ve plan değişikliklerine uygulanmaz.", EN: "Coupons apply to new subscriptions, not to your current one or to plan changes." },
    couponApplied: { TR: "{code} uygulandı: %{percent} indirim · {plans} · {payments}", EN: "{code} applied: {percent}% off · {plans} · {payments}" },
    couponRemove: { TR: "Kaldır", EN: "Remove" },
    couponAllPlans: { TR: "Plus ve Pro", EN: "Plus and Pro" },
    couponFirst: { TR: "ilk ödemede", EN: "on the first payment" },
    couponAll: { TR: "her ödemede", EN: "on every payment" },
    couponCount: { TR: "ilk {count} ödemede", EN: "on the first {count} payments" },
    couponOnCard: { TR: "{code} kuponuyla, {payments}", EN: "With {code}, {payments}" },
    couponInvalid: { TR: "Bu kupon kodu geçerli değil. Kodu kontrol edip tekrar dene.", EN: "This coupon code isn't valid. Check the code and try again." },
    couponExpired: { TR: "Bu kuponun süresi dolmuş.", EN: "This coupon has expired." },
    couponUsedUp: { TR: "Bu kuponun kullanım hakkı dolmuş.", EN: "This coupon has no uses left." },
    couponPlan: { TR: "Bu kupon seçtiğin planda geçerli değil.", EN: "This coupon isn't valid for the plan you picked." },
    failureTeam: { TR: "Ekip için: bu isteğin ayrıntısı Yönetici Paneli › Abonelikler › Paddle bölümündeki \"Son sunucu hataları\" listesinde (yanıt hiç gelmediyse \"Son ödeme ekranı hataları\"nda) ve Vercel günlüklerinde.", EN: "For the team: the details of this request are under Admin Panel › Subscriptions › Paddle in \"Recent server errors\" (or, when no answer came at all, in \"Recent checkout errors\") and in the Vercel logs." },
    testMode: { TR: "Test modu: satışlar henüz herkese açık değil; bu sayfayı yalnızca Hanogt ekibi ve test kullanıcıları satın alınabilir görüyor.", EN: "Test mode: sales aren't open to everyone yet; only the Hanogt team and testers see these plans as buyable." },
    sandbox: { TR: "Paddle sandbox: gerçek ödeme alınmaz, test kartıyla dene (4242 4242 4242 4242).", EN: "Paddle sandbox: no real payments; use a test card (4242 4242 4242 4242)." },
    alreadySubscribed: { TR: "Zaten bir aboneliğin var; planını bu sayfadan değiştirebilirsin.", EN: "You already have a subscription; you can change your plan on this page." },
    subscriptionPaused: { TR: "Duraklatılmış bir aboneliğin var; yenisini almak yerine onu sürdürebilirsin.", EN: "You have a paused subscription; resume it instead of buying a new one." },
    customerUnverified: { TR: "Bu e-posta adresiyle Paddle'da daha önce açılmış bir müşteri kaydı var. Güvenliğin için hesabının e-postasını doğrulamamız gerekiyor: bir kez Google ile giriş yap ya da destek talebi aç, ekibimiz kaydı hesabına bağlasın.", EN: "Paddle already has a customer record with this e-mail address. For your security we need to verify your account's address: sign in with Google once, or open a support ticket so our team can link the record to your account." },
    customerConflict: { TR: "Bu hesabın Paddle müşteri kaydı başka bir hesaba bağlı. Destek talebi aç; ekibimiz düzeltsin.", EN: "This account's Paddle customer record is linked to another account. Open a support ticket so our team can sort it out." },
    paymentDeclined: { TR: "Paddle kayıtlı ödeme yönteminden ücreti alamadı (kart reddedildi). Ödeme yöntemini güncelleyip tekrar dene.", EN: "Paddle couldn't charge your saved payment method (card declined). Update it and try again." },
    reload: { TR: "Sayfayı yenile", EN: "Refresh the page" },
    paymentLinkSignedOut: { TR: "Ödemen alındı, teşekkürler. Plan, ödemeyi yaptığın e-postayla açılmış Hanogt hesabında etkinleşir; görmek için giriş yap.", EN: "Payment received, thank you. The plan becomes active on the Hanogt account with the e-mail you paid with; sign in to see it." },
    paymentLinkDone: { TR: "Ödemen alındı, teşekkürler.", EN: "Payment received, thank you." },
    paymentMethodError: { TR: "Seçilen ödeme yöntemi kullanılamadı. Başka bir yöntem dene; sorun sürerse destek talebi aç.", EN: "The chosen payment method can't be used. Try another one; if it keeps happening, open a support ticket." },
    staffPlanHigher: { TR: "Daha yüksek bir plan ekip tarafından tanımlandı", EN: "A higher plan was assigned by the team" },
    changeInPortal: { TR: "Bu abonelik bu sayfadan değiştirilemiyor; \"Aboneliği yönet\"i kullan.", EN: "This subscription can't be changed on this page; use \"Manage subscription\"." },
    planUnavailable: { TR: "Bu plan şu anda satışta değil.", EN: "This plan isn't on sale right now." },
    billingUnavailable: { TR: "Ödemeler şu anda kapalı. Biraz sonra tekrar dene.", EN: "Payments are switched off right now. Try again later." },
    rateLimited: { TR: "Çok fazla deneme oldu. Bir dakika sonra tekrar dene.", EN: "Too many attempts. Try again in a minute." },
    signedOut: { TR: "Oturumun sona ermiş; yeniden giriş yap.", EN: "Your session has ended; please sign in again." },
    paddleError: { TR: "Paddle şu anda yanıt vermiyor ({code}). Biraz sonra tekrar dene.", EN: "Paddle isn't responding right now ({code}). Try again in a moment." },
    paddleRefused: { TR: "Paddle isteği kabul etmedi ({code}). Biraz sonra tekrar dene; sorun sürerse destek talebi aç.", EN: "Paddle didn't accept the request ({code}). Try again in a moment; if it keeps happening, open a support ticket." },
    paddleBlocked: { TR: "Ödeme ekranı yüklenemedi: Paddle'ın ödeme betiği tarayıcına ulaşmadı. Reklam engelleyici, tarayıcının izleme koruması ya da ağ ayarların (ör. kurum ağı, VPN, DNS filtresi) cdn.paddle.com adresini engelliyor olabilir. Bu site için izin verip tekrar dene.", EN: "The checkout couldn't load: Paddle's checkout script didn't reach your browser. An ad blocker, your browser's tracking protection or your network (e.g. a work network, VPN or DNS filter) may be blocking cdn.paddle.com. Allow it for this site and try again." },
    paddleBlockedUrl: { TR: "Ödeme ekranı yüklenemedi: tarayıcın {url} adresini engelledi. Reklam ya da betik engelleyiciyi veya tarayıcının izleme korumasını bu site için kapatıp tekrar dene; sorun sürerse destek talebi aç.", EN: "The checkout couldn't load: your browser blocked {url}. Turn off your ad or script blocker or your browser's tracking protection for this site and try again; if it keeps happening, open a support ticket." },
    paddleStart: { TR: "Ödeme ekranı başlatılamadı: Paddle yüklendi ama çalıştırılamadı. Biraz sonra tekrar dene; sorun sürerse destek talebi aç.", EN: "The checkout couldn't start: Paddle loaded but couldn't be started. Try again in a moment; if it keeps happening, open a support ticket." },
    paddleStartTeam: { TR: "Ekip için: Vercel'deki istemci tarafı jeton (NEXT_PUBLIC_PADDLE_CLIENT_TOKEN) başka bir Paddle hesabına ya da öbür ortama (Sandbox/Canlı) ait olabilir. Yönetici Paneli › Abonelikler › Paddle bölümündeki jeton denetimine bakın.", EN: "For the team: the client-side token in Vercel (NEXT_PUBLIC_PADDLE_CLIENT_TOKEN) may belong to another Paddle account or to the other environment (sandbox/live). See the token check under Admin Panel › Subscriptions › Paddle." },
    paddleOpen: { TR: "Ödeme ekranı açılamadı. Sayfayı yenileyip tekrar dene; sorun sürerse destek talebi aç.", EN: "The checkout couldn't open. Refresh the page and try again; if it keeps happening, open a support ticket." },
    checkoutError: { TR: "Ödeme ekranı bir hata bildirdi: {detail}", EN: "The checkout reported an error: {detail}" },
    checkoutErrorGeneric: { TR: "Ödeme ekranında bir hata oluştu. Tekrar dene; sorun sürerse destek talebi aç.", EN: "Something went wrong in the checkout. Try again; if it keeps happening, open a support ticket." },
    checkoutValidationTeam: { TR: "Ekip için: Paddle ödeme ekranını açarken isteğin bir alanını kabul etmedi (alanlar yukarıda). Olası nedenlerden biri, tarayıcıdaki istemci tarafı jetonun (NEXT_PUBLIC_PADDLE_CLIENT_TOKEN) işlemi oluşturan API anahtarından farklı bir Paddle hesabına ya da ortama ait olması; Yönetici Paneli › Abonelikler › Paddle'daki jeton denetimine bak.", EN: "For the team: Paddle refused a field of the request while opening the checkout (the fields are above). One possible cause is a client-side token (NEXT_PUBLIC_PADDLE_CLIENT_TOKEN) from another Paddle account or environment than the API key that created the transaction; see the token check under Admin Panel › Subscriptions › Paddle." },
    technical: { TR: "Teknik ayrıntı: {stage}: {message}", EN: "Technical detail: {stage}: {message}" },
    unavailable: { TR: "Plan bilgileri şu anda alınamıyor; aşağıdaki fiyatlar henüz kesinleşmedi.", EN: "Plan details can't be loaded right now; the prices below aren't final yet." },
    taxNote: { TR: "Fiyatlara bulunduğun ülkenin vergileri dahildir; kesin tutar ödeme ekranında gösterilir. Ödemeler, Kayıtlı Satıcımız (Merchant of Record) Paddle.com tarafından alınır.", EN: "Prices include the taxes of your country; the exact amount is shown at checkout. Payments are taken by Paddle.com, our Merchant of Record." },
    refundPolicy: { TR: "İade Politikası", EN: "Refund Policy" },
    terms: { TR: "Kullanım Şartları", EN: "Terms of Use" },
    faqTitle: { TR: "Sık sorulanlar", EN: "Questions" },
    q1: { TR: "Ödeme ne zaman başlayacak?", EN: "When will payments start?" },
    a1: { TR: "Henüz bir tarih yok. Planlar açıldığında bu sayfada, güncelleme günlüğünde ve \"Açılınca haber ver\" dediysen bildirimlerinde duyuracağız. O güne kadar hiçbir ücret alınmaz.", EN: "There's no date yet. When plans open we'll announce it on this page, in the changelog and, if you pressed \"Notify me\", in your notifications. Until then nothing is charged." },
    q2: { TR: "Ücretsiz plan kalkacak mı?", EN: "Will the free plan go away?" },
    a2: { TR: "Hayır. Kod editörü, oyun motoru, Arcade, Media ve Hanogt Social ücretsiz planda kalmaya devam edecek; Hanogt AI da ücretsiz planda haftada 50 mesajla kullanılabilir.", EN: "No. The code editor, the game engine, the Arcade, Media and Hanogt Social stay in the free plan, and Hanogt AI is available there with 50 messages a week." },
    q3: { TR: "Kupon kodum var, ne yapmalıyım?", EN: "I have a coupon code. What do I do?" },
    a3: { TR: "Kodunu sakla; planlar açıldığında satın alma sırasında kullanabileceksin. Kuponların bitiş tarihi kupon verilirken belirtilir.", EN: "Keep it; you'll be able to use it at checkout once plans open. A coupon's expiry date is given with the coupon." },
    q4: { TR: "Planım nasıl tanımlandı?", EN: "How did I get a plan?" },
    a4: { TR: "Ekip; testçilere, katkı verenlere ve yarışma kazananlarına planı elle tanımlayabilir. Tanımlanan planın avantajları satın alınanla aynıdır: daha yüksek Hanogt AI sınırı ve daha uzun yanıtlar, daha fazla proje ve grup, tek seferde daha çok dosya ve sunucuda daha büyük çalıştırmalar, daha büyük gruplar, daha uzun mesajlar ve gruplarda daha uzun Hanogt AI yanıtları, daha çok yıldızlı mesaj, daha kalabalık ve daha uzun ekip oturumları, rozetsiz oyun dışa aktarma, kendi API anahtarınla bağlantılar, geliştirici API'si, profil rozeti, destekte öncelik ve Pro'da erken erişim.", EN: "The team can assign a plan by hand to testers, contributors and contest winners. An assigned plan has the same benefits as a bought one: a higher Hanogt AI limit and longer answers, more projects and groups, more files run at once and bigger server runs, bigger groups, longer messages and longer Hanogt AI answers in groups, more starred messages, larger and longer team sessions, game exports without the badge, connections with your own API keys, the developer API, the profile badge, support priority and, on Pro, early access." },
    bq1: { TR: "Ödemeyi kim alıyor?", EN: "Who takes the payment?" },
    ba1: { TR: "Ödemeler Paddle üzerinden alınır. Paddle.com, Hanogt Codev siparişlerinin Kayıtlı Satıcısıdır (Merchant of Record): ödemeyi alır, faturayı keser ve vergileri hesaplar. Kart bilgilerin Hanogt Codev'e hiç ulaşmaz.", EN: "Payments go through Paddle. Paddle.com is the Merchant of Record for Hanogt Codev orders: it takes the payment, issues the invoice and handles taxes. Your card details never reach Hanogt Codev." },
    bq2: { TR: "Aboneliğimi nasıl iptal ederim?", EN: "How do I cancel?" },
    ba2: { TR: "Bu sayfada \"Aboneliği yönet\"e bas; Paddle'ın müşteri portalından aboneliğini iptal edebilirsin. İptal, ödediğin dönemin sonunda geçerli olur ve o güne kadar avantajların sürer.", EN: "Press \"Manage subscription\" on this page and cancel in Paddle's customer portal. Cancellation takes effect at the end of the period you paid for, and your benefits last until then." },
    bq3: { TR: "İade alabilir miyim?", EN: "Can I get a refund?" },
    ba3: { TR: "Bir aboneliğin ilk ödemesinden sonraki 14 gün içinde iade isteyebilirsin. Ayrıntılar İade Politikası'nda.", EN: "You can ask for a refund within 14 days of a subscription's first payment. The details are in the Refund Policy." },
    bq4: { TR: "Planımı değiştirebilir miyim?", EN: "Can I change my plan?" },
    ba4: { TR: "Evet. Plus ile Pro arasında ya da aylık ile yıllık ödeme arasında geçebilirsin. Kalan süren için fark orantılı hesaplanır ve onaylamadan önce gösterilir.", EN: "Yes. You can move between Plus and Pro, or between monthly and yearly billing. The difference for the rest of your period is prorated and shown before you confirm." },
    q5: { TR: "Kendi API anahtarımla gönderdiğim mesajlar hakkımdan düşer mi?", EN: "Do messages through my own API key use my allowance?" },
    a5: { TR: "Evet. Plus ve Pro'da kendi anahtarınla bağladığın sağlayıcılarla gönderdiğin mesajların ayrı bir sınırı yoktur: sohbet, geliştirici API'si ve gruplardaki Hanogt AI ile aynı Hanogt AI mesaj hakkından düşer. Sağlayıcı yanıt vermezse mesaj hakkına geri eklenir; sağlayıcının ücretleri sana aittir.", EN: "Yes. On Plus and Pro, messages through the providers you connect with your own key have no limit of their own: they use the same Hanogt AI allowance as the chat, the developer API and Hanogt AI in groups. If the provider doesn't answer, the message is given back; the provider's charges are yours." },
    q6: { TR: "Grup sınırları kimin planına göre?", EN: "Whose plan sets a group's limits?" },
    a6: { TR: "Grubun sahibinin planına göre: üye sayısı Ücretsiz'de 25, Plus'ta 100, Pro'da 250; sabitlenmiş mesaj, özel bot komutu ve AutoMod yasaklı kelime sınırları da büyür. Sahibin planı düşerse grupta hiçbir şey silinmez; yalnızca sınırın altına inene kadar yenisi eklenemez.", EN: "The group owner's: 25 members on Free, 100 on Plus and 250 on Pro, and the limits for pinned messages, custom bot commands and AutoMod banned words grow too. If the owner's plan goes down nothing in the group is removed; nothing new can be added until it is under the limit." },
    bq5: { TR: "Kupon kodumu nerede kullanırım?", EN: "Where do I use a coupon code?" },
    ba5: { TR: "Bu sayfada \"Kupon kodun var mı?\"ya bas, kodunu yazıp Uygula'ya bas: indirimli tutar planın üzerinde, ödeme ekranında da indirim olarak görünür. İstersen kodu ödeme ekranındaki \"İndirim ekle\"ye de yazabilirsin. Kuponun hangi planda ve kaç ödemede geçerli olduğu kod uygulanınca yazılır. Kuponlar yeni aboneliklerde geçerlidir; mevcut aboneliğe ya da plan değişikliğine uygulanmaz.", EN: "On this page press \"Have a coupon code?\", enter it and press Apply: the discounted amount shows on the plan and as a discount at checkout. You can also enter it with \"Add discount\" at checkout. Which plan and how many payments it covers is shown once it's applied. Coupons apply to new subscriptions, not to an existing one or to plan changes." },
} satisfies Record<string, Copy>;

export const PLAN_RANK: Record<PlanId, number> = { free: 0, plus: 1, pro: 2 };

/** How many payments a coupon covers, in words ("on the first payment"). */
export function couponPayments(recur: CouponRecur): { copy: Copy; vars?: Record<string, number> } {
    return recur === "first" ? { copy: C.couponFirst } : recur === "all" ? { copy: C.couponAll } : { copy: C.couponCount, vars: { count: recur } };
}

/** Sign-in that comes back here, with a link's coupon code kept so it applies afterwards. */
export function loginHref(linkCoupon: string) {
    const back = linkCoupon ? `/plans?coupon=${encodeURIComponent(linkCoupon)}` : "/plans";
    return `/login?callbackUrl=${encodeURIComponent(back)}`;
}
