"use client";

import { useCallback } from "react";
import { useI18n } from "@/lib/i18n";

/**
 * Engine UI strings: [Türkçe, English]. Other site languages are looked up in the
 * copy packs (src/locales/copy) by the English text and fall back to English.
 */
const TEXT = {
    back: ["Geri", "Back"],
    hub: ["Projeler", "Projects"],
    save: ["Kaydet", "Save"],
    saving: ["Kaydediliyor…", "Saving…"],
    saved: ["Kaydedildi", "Saved"],
    unsaved: ["Kaydedilmemiş değişiklikler", "Unsaved changes"],
    saveFailed: ["Kaydedilemedi", "Save failed"],
    savedLocal: ["Bu cihaza kaydedildi", "Saved on this device"],
    cloud: ["Bulut", "Cloud"],
    local: ["Yerel", "Local"],
    undo: ["Geri al", "Undo"],
    redo: ["Yinele", "Redo"],
    play: ["Oynat", "Play"],
    pause: ["Duraklat", "Pause"],
    resume: ["Devam", "Resume"],
    step: ["Bir kare ilerle", "Step one frame"],
    stop: ["Durdur", "Stop"],
    restart: ["Yeniden başlat", "Restart"],
    move: ["Taşı (W)", "Move (W)"],
    rotate: ["Döndür (E)", "Rotate (E)"],
    scale: ["Ölçekle (R)", "Scale (R)"],
    worldSpace: ["Dünya ekseni", "World space"],
    localSpace: ["Yerel eksen", "Local space"],
    settings: ["Ayarlar", "Settings"],
    export: ["Dışa aktar", "Export"],
    exportJson: ["Proje dosyası (.json)", "Project file (.json)"],
    exportHtml: ["Oynanabilir HTML oyunu", "Playable HTML game"],
    importProject: ["Proje içe aktar", "Import project"],
    publish: ["Arcade'de yayınla", "Publish to Arcade"],
    publishShort: ["Yayınla", "Publish"],
    published: ["Yayında", "Published"],
    docs: ["Belgeler", "Docs"],
    scene: ["Sahne", "Scene"],
    game: ["Oyun", "Game"],
    hierarchy: ["Hiyerarşi", "Hierarchy"],
    scenes: ["Sahneler", "Scenes"],
    inspector: ["Inspector", "Inspector"],
    project: ["Proje", "Project"],
    console: ["Konsol", "Console"],
    search: ["Ara…", "Search…"],
    create: ["Oluştur", "Create"],
    createChild: ["Alt nesne oluştur", "Create child"],
    duplicate: ["Çoğalt (Ctrl+D)", "Duplicate (Ctrl+D)"],
    rename: ["Yeniden adlandır (F2)", "Rename (F2)"],
    delete: ["Sil (Del)", "Delete (Del)"],
    copy: ["Kopyala (Ctrl+C)", "Copy (Ctrl+C)"],
    paste: ["Yapıştır (Ctrl+V)", "Paste (Ctrl+V)"],
    makePrefab: ["Prefab oluştur", "Create prefab"],
    applyPrefab: ["Prefab'ı güncelle", "Apply to prefab"],
    focus: ["Odakla (F)", "Focus (F)"],
    unparent: ["Kök nesne yap", "Move to root"],
    emptyObject: ["Boş Nesne", "Empty Object"],
    spriteSquare: ["Sprite (Kare)", "Sprite (Square)"],
    spriteCircle: ["Sprite (Daire)", "Sprite (Circle)"],
    noSelection: ["Düzenlemek için sahneden veya hiyerarşiden bir nesne seçin.", "Select an object in the scene or hierarchy to edit it."],
    multiSelection: ["nesne seçildi", "objects selected"],
    addComponent: ["Bileşen ekle", "Add component"],
    addScript: ["Script ekle", "Add script"],
    newScript: ["Yeni script", "New script"],
    removeComponent: ["Bileşeni kaldır", "Remove component"],
    moveUp: ["Yukarı taşı", "Move up"],
    moveDown: ["Aşağı taşı", "Move down"],
    resetComponent: ["Sıfırla", "Reset"],
    active: ["Aktif", "Active"],
    name: ["Ad", "Name"],
    tag: ["Etiket", "Tag"],
    position: ["Konum", "Position"],
    rotation: ["Dönüş", "Rotation"],
    scaleLabel: ["Ölçek", "Scale"],
    none: ["(Yok)", "(None)"],
    missing: ["(Eksik)", "(Missing)"],
    scripts: ["Scriptler", "Scripts"],
    prefabs: ["Prefab'lar", "Prefabs"],
    textures: ["Dokular", "Textures"],
    uploadTexture: ["Görsel yükle", "Upload image"],
    newScene: ["Yeni sahne", "New scene"],
    startScene: ["Başlangıç sahnesi", "Start scene"],
    setStartScene: ["Başlangıç sahnesi yap", "Set as start scene"],
    openScript: ["Kodu aç", "Open code"],
    instantiate: ["Sahneye ekle", "Add to scene"],
    clear: ["Temizle", "Clear"],
    collapse: ["Birleştir", "Collapse"],
    errors: ["Hatalar", "Errors"],
    warnings: ["Uyarılar", "Warnings"],
    messages: ["Mesajlar", "Messages"],
    consoleEmpty: ["Konsol boş. Debug.Log çıktıları ve hatalar burada görünür.", "The console is empty. Debug.Log output and errors appear here."],
    compileErrors: ["Derleme hataları var", "There are compile errors"],
    compiledOk: ["Tüm scriptler derlendi", "All scripts compiled"],
    playBlocked: ["Oyunu başlatmadan önce derleme hatalarını düzeltin.", "Fix compile errors before playing."],
    playingNote: ["Oyun çalışıyor — düzenleme için durdurun.", "The game is running — stop it to edit."],
    grid: ["Izgara", "Grid"],
    colliders: ["Çarpıştırıcılar", "Colliders"],
    icons: ["Simgeler", "Icons"],
    resetView: ["Görünümü sıfırla", "Reset view"],
    confirmDelete: ["Silinsin mi?", "Delete?"],
    confirmDeleteScript: ["Bu script silinsin mi? Onu kullanan bileşenler de kaldırılacak.", "Delete this script? Components using it will be removed too."],
    confirmDeleteProject: ["Bu proje kalıcı olarak silinsin mi?", "Delete this project permanently?"],
    projectSettings: ["Proje ayarları", "Project settings"],
    sceneSettings: ["Sahne ayarları", "Scene settings"],
    close: ["Kapat", "Close"],
    cancel: ["İptal", "Cancel"],
    ok: ["Tamam", "OK"],
    templates: ["Şablonlar", "Templates"],
    newProject: ["Yeni proje", "New project"],
    myProjects: ["Projelerim", "My projects"],
    open: ["Aç", "Open"],
    loading: ["Yükleniyor…", "Loading…"],
    projectName: ["Proje adı", "Project name"],
    createProject: ["Projeyi oluştur", "Create project"],
    signInForCloud: ["Projelerin buluta kaydedilmesi için giriş yapın. Giriş yapmadan oluşturulan projeler bu tarayıcıda saklanır.", "Sign in to save projects to the cloud. Projects created as a guest are stored in this browser."],
    noProjects: ["Henüz proje yok. Bir şablonla başlayın!", "No projects yet. Start from a template!"],
    lastEdited: ["Son düzenleme", "Last edited"],
    objects: ["nesne", "objects"],
    publishTitle: ["Başlık", "Title"],
    publishDescription: ["Açıklama", "Description"],
    publishNow: ["Yayınla", "Publish"],
    updatePublished: ["Yayını güncelle", "Update listing"],
    unpublish: ["Yayından kaldır", "Unpublish"],
    publishedAt: ["Arcade'de yayında", "Live on the Arcade"],
    publishNeedsCloud: ["Arcade'de yayınlamak için giriş yapıp projeyi buluta kaydedin.", "Sign in and save the project to the cloud to publish it."],
    viewInArcade: ["Arcade'de aç", "Open in Arcade"],
    fps: ["FPS göster", "Show FPS"],
    shadows: ["Gölgeler", "Shadows"],
    antialias: ["Kenar yumuşatma", "Antialiasing"],
    pixelArt: ["Piksel sanat modu", "Pixel art mode"],
    touchControls: ["Dokunmatik kontroller", "Touch controls"],
    aspect: ["En-boy oranı", "Aspect ratio"],
    background: ["Arka plan", "Background"],
    solid: ["Düz renk", "Solid"],
    gradient: ["Gradyan", "Gradient"],
    topColor: ["Üst renk", "Top color"],
    bottomColor: ["Alt renk", "Bottom color"],
    ambient: ["Ortam ışığı", "Ambient light"],
    fog: ["Sis", "Fog"],
    gravity: ["Yerçekimi", "Gravity"],
    fixedStep: ["Fizik adımı (sn)", "Physics step (s)"],
    description: ["Açıklama", "Description"],
    shortcuts: ["Kısayollar", "Shortcuts"],
    apply: ["Uygula", "Apply"],
    compile: ["Derle", "Compile"],
    line: ["satır", "line"],
    scriptFields: ["Inspector alanları", "Inspector fields"],
    noFields: ["Bu script'te public alan yok.", "This script has no public fields."],
    classNotFound: ["Script'te MonoBehaviour sınıfı bulunamadı.", "No MonoBehaviour class found in the script."],
    fitCollider: ["Görsele sığdır", "Fit to visual"],
    previewSound: ["Sesi dinle", "Preview sound"],
    dropHere: ["Sahneye eklemek için bırakın", "Drop to add to the scene"],
    readOnlyPlaying: ["Oynatma modunda düzenleme kapalı", "Editing is disabled in play mode"],
    unsavedLeave: ["Kaydedilmemiş değişiklikler var. Çıkmak istiyor musunuz?", "You have unsaved changes. Leave anyway?"],
    welcomeTitle: ["Hanogt Engine'e hoş geldin", "Welcome to Hanogt Engine"],
    welcomeText: ["Unity benzeri, tarayıcıda çalışan 2D/3D oyun motoru. C# veya C++ ile script yaz, anında oyna, Arcade'de paylaş.", "A Unity-like 2D/3D game engine in your browser. Script in C# or C++, play instantly and share on the Arcade."],
    arcade: ["Arcade", "Arcade"],
    guide: ["Kılavuz", "Guide"],
    rename2: ["Yeniden adlandır", "Rename"],
    deleteLabel: ["Sil", "Delete"],
    duplicateLabel: ["Çoğalt", "Duplicate"],
    thumbnail: ["Kapak görseli", "Thumbnail"],
    captureThumbnail: ["Sahneden yakala", "Capture from scene"],
    guest: ["Misafir", "Guest"],
    hCreateEntity: ["Nesne oluştur", "Create object"],
    hHideEntity: ["Nesneyi gizle", "Hide object"],
    hShowEntity: ["Nesneyi göster", "Show object"],
    hReparent: ["Hiyerarşiyi düzenle", "Edit hierarchy"],
    hUnparent: ["Kök nesne yap", "Move to root"],
    hEditScript: ["Script düzenle", "Edit script"],
    hPaste: ["Yapıştır", "Paste"],
    hImportProject: ["Proje içe aktar", "Import project"],
    hUploadTexture: ["Doku yükle", "Upload texture"],
    hOpenScene: ["Sahne aç", "Open scene"],
    hTransform: ["Dönüşüm", "Transform"],
    hCreateSprite: ["Sprite oluştur", "Create sprite"],
    hComponentEnabled: ["Bileşen etkinliği", "Toggle component"],
    hResetComponent: ["Bileşeni sıfırla", "Reset component"],
    hMoveComponent: ["Bileşeni taşı", "Move component"],
    hRemoveComponent: ["Bileşeni kaldır", "Remove component"],
    hScriptName: ["Script adı", "Script name"],
    hPrefabName: ["Prefab adı", "Prefab name"],
    hTextureName: ["Doku adı", "Texture name"],
    hSceneName: ["Sahne adı", "Scene name"],
    hStartScene: ["Başlangıç sahnesi", "Start scene"],
    hEditComponent: ["Bileşeni düzenle", "Edit component"],
    hFitCollider: ["Çarpıştırıcıyı sığdır", "Fit collider"],
    toggleExpand: ["Aç/kapat", "Expand/collapse"],
    hide: ["Gizle", "Hide"],
    show: ["Göster", "Show"],
    selectScript: ["Script seçin", "Select a script"],
    saveConflict: ["Proje başka bir sekmede/cihazda değişti. Sayfayı yenileyip güncel sürümü yükleyin; bu sekmedeki değişiklikleri kaybetmemek için önce JSON olarak dışa aktarabilirsiniz.", "This project changed in another tab or on another device. Reload to get the latest version; export it as JSON first to keep the changes made in this tab."],
    clipboardFailed: ["Pano içeriği okunamadı.", "Couldn't read the clipboard."],
    htmlExported: ["Oynanabilir HTML dosyası indirildi.", "Playable HTML file downloaded."],
    exportFailed: ["Dışa aktarılamadı.", "Export failed."],
    importConfirm: ["\"{name}\" içe aktarılsın mı? Bu projenin içeriği değiştirilecek (geri alınabilir).", "Import \"{name}\"? This project's content will be replaced (you can undo it)."],
    imported: ["Proje içe aktarıldı.", "Project imported."],
    importFailed: ["İçe aktarılamadı.", "Import failed."],
    unmute: ["Sesi aç", "Unmute"],
    mute: ["Sesi kapat", "Mute"],
    editorPanels: ["Editör panelleri", "Editor panels"],
    codeTabs: ["Kod", "Code"],
    textureUploaded: ["\"{name}\" yüklendi ({size}).", "\"{name}\" uploaded ({size})."],
    imageUploadFailed: ["Görsel yüklenemedi.", "The image couldn't be uploaded."],
    noScriptsYet: ["Henüz script yok — C# veya C++ ile başlayın.", "No scripts yet — start with C# or C++."],
    prefabHint: ["Hiyerarşide bir nesneye sağ tıklayıp “{action}” seçin.", "Right-click an object in the Hierarchy and choose “{action}”."],
    texturesHint: ["PNG/JPG/WEBP yükleyip sprite veya materyallerde kullanın. Sahneye sürükleyebilirsiniz.", "Upload PNG/JPG/WEBP images to use in sprites or materials. You can drag them into the scene."],
    webglFailed: ["WebGL başlatılamadı. Tarayıcınızın donanım hızlandırmasını açın.", "WebGL couldn't start. Turn on hardware acceleration in your browser."],
    sceneHelp2D: ["Sol tık: seç · Sürükle: kaydır · Tekerlek: yakınlaş · F: odakla", "Left click: select · Drag: pan · Wheel: zoom · F: focus"],
    sceneHelp3D: ["Sol tık: seç · Sol sürükle: döndür · Sağ sürükle: kaydır · Tekerlek: yakınlaş · F: odakla", "Left click: select · Left drag: orbit · Right drag: pan · Wheel: zoom · F: focus"],
    componentMenu: ["Bileşen menüsü", "Component menu"],
    prefabUsage1: ["Script'lerde ", "Assign this prefab to a "],
    prefabUsage2: [" alanına bu prefab'ı atayıp ", " field in a script and spawn copies in the game with "],
    prefabUsage3: [" ile oyunda çoğaltabilirsiniz.", "."],
    sceneSetting: ["Sahne ayarı", "Scene setting"],
    compileErrorsFirst: ["{count} derleme hatası — ilk: satır {line}: {message}", "{count} compile errors — first: line {line}: {message}"],
    publishFailed: ["Yayınlanamadı.", "Publishing failed."],
    allowRemix: ["Remikslemelere izin ver", "Allow remixes"],
    allowRemixHint: ["Açarsan diğer oyuncular oyununu Remix ile kendi projelerine kopyalayıp değiştirebilir; yayımladıklarında sana atıf yapılır. Kapalıyken Remix düğmesi görünmez ve sunucu kopyalamayı reddeder.", "If it's on, other players can copy your game into their own projects with Remix and change it; when they publish, you're credited. While it's off, the Remix button doesn't appear and the server refuses copies."],
    actionFailed: ["İşlem başarısız.", "Action failed."],
    publishNotice: ["Yayınlanan oyunlar Arcade'de herkese açık görünür; kodunuz oyunu çalıştırmak için oyuncuların tarayıcısına gönderilir. Kişisel veri, parola veya gizli anahtar paylaşmayın. Kullanım şartlarına aykırı içerik kaldırılır.", "Published games are public on the Arcade, and your code is sent to players' browsers to run the game. Don't share personal data, passwords or secret keys. Content that breaks the Terms of Use is removed."],
    editorOrigin: ["Editör", "Editor"],
    frame: ["kare", "frame"],
    cloudLoadFailed: ["Bulut projeleri yüklenemedi.", "Cloud projects couldn't be loaded."],
    createFailed: ["Proje oluşturulamadı.", "The project couldn't be created."],
    downloadFailed: ["İndirilemedi.", "Download failed."],
    signIn: ["Giriş yap", "Sign in"],
    savesToCloud: ["Proje hesabınıza (bulut) kaydedilecek.", "The project will be saved to your account (cloud)."],
    savesToBrowser: ["Proje bu tarayıcıya kaydedilecek.", "The project will be saved in this browser."],
    engineLoading: ["Hanogt Engine yükleniyor…", "Loading Hanogt Engine…"],
    projectNotInBrowser: ["Bu proje bu tarayıcıda bulunamadı. Başka bir cihazda veya tarayıcıda oluşturulmuş olabilir.", "This project isn't stored in this browser. It may have been created on another device or browser."],
    signInForCloudProjects: ["Bulut projelerini açmak için giriş yapmalısınız.", "Sign in to open cloud projects."],
    projectLoadFailed: ["Proje yüklenemedi.", "The project couldn't be loaded."],
    projectOpenFailed: ["Proje açılamadı", "Couldn't open the project"],
    projectLoading: ["Proje yükleniyor…", "Loading project…"],
    retry: ["Tekrar dene", "Try again"],
    // V3: editor tools
    whatsNew: ["V3'te yenilikler", "What's new in V3"],
    snapping: ["Yakalama", "Snapping"],
    snapToggle: ["Izgaraya yakala", "Snap to grid"],
    snapMove: ["Taşıma adımı", "Move step"],
    snapRotate: ["Döndürme adımı (°)", "Rotate step (°)"],
    snapScale: ["Ölçek adımı", "Scale step"],
    stats: ["İstatistikler", "Stats"],
    statsFrame: ["Kare süresi", "Frame time"],
    statsObjects: ["Nesneler", "Objects"],
    statsBodies: ["Fizik gövdeleri", "Physics bodies"],
    statsDrawCalls: ["Çizim çağrıları", "Draw calls"],
    statsTriangles: ["Üçgenler", "Triangles"],
    statsTweens: ["Tween / zamanlayıcı", "Tweens / timers"],
    statsParticles: ["Parçacıklar", "Particles"],
    showEffects: ["Ekran efektlerini göster", "Show screen effects"],
    // V3: tile painter
    paintTiles: ["Sahnede boya", "Paint in scene"],
    stopPainting: ["Boyamayı bitir", "Stop painting"],
    toolPaint: ["Fırça", "Brush"],
    toolErase: ["Silgi", "Eraser"],
    toolRect: ["Dikdörtgen", "Rectangle"],
    toolPick: ["Damlalık", "Picker"],
    palette: ["Palet", "Palette"],
    addTile: ["Karo ekle", "Add tile"],
    removeTile: ["Karoyu sil", "Delete tile"],
    tileKey: ["Karakter", "Key"],
    tileSolid: ["Çarpışır / tetikler", "Collides / triggers"],
    tileFrame: ["Atlas karesi", "Atlas cell"],
    plainColor: ["Düz renk", "Plain color"],
    cellSize: ["Hücre boyutu", "Cell size"],
    atlas: ["Doku atlası", "Texture atlas"],
    atlasGrid: ["Sütun × satır", "Columns × rows"],
    tilemapInfo: ["{tiles} karo · {width}×{height} hücre", "{tiles} tiles · {width}×{height} cells"],
    clearTiles: ["Tümünü temizle", "Clear all"],
    confirmClearTiles: ["Tüm karolar silinsin mi?", "Delete every tile?"],
    paintHint: ["Sol tık / dokunma: boya · Shift + tık: sil · Sağ sürükle: kaydır · Esc: bitir", "Left click / touch: paint · Shift + click: erase · Right drag: pan · Esc: done"],
    hPaintTiles: ["Karo boya", "Paint tiles"],
    hEditPalette: ["Paleti düzenle", "Edit palette"],
    tilemap2dHint: ["Tilemap'ler 2D oyunlar için tasarlandı; 3D'de nesnenin XY düzleminde çizilir.", "Tilemaps are made for 2D games; in 3D they are drawn on the object's XY plane."],
    // V3: animation
    clips: ["Klipler", "Clips"],
    addClip: ["Klip ekle", "Add clip"],
    emptyClip: ["Boş klip", "Empty clip"],
    duration: ["Süre (sn)", "Duration (s)"],
    wrapMode: ["Tekrar", "Wrap mode"],
    wrapOnce: ["Bir kez", "Once"],
    wrapLoop: ["Döngü", "Loop"],
    wrapPingPong: ["Git-gel", "Ping-pong"],
    addTrack: ["Kanal ekle", "Add track"],
    addKey: ["Anahtar kare ekle", "Add keyframe"],
    removeKey: ["Anahtar kareyi sil", "Remove keyframe"],
    removeTrack: ["Kanalı sil", "Remove track"],
    removeClip: ["Klibi sil", "Remove clip"],
    defaultClip: ["Başlangıç klibi", "Default clip"],
    playOnStart: ["Başlangıçta oynat", "Play on start"],
    speed: ["Hız", "Speed"],
    easing: ["Yumuşatma", "Easing"],
    time: ["Zaman", "Time"],
    presetBob: ["Süzülme (yukarı-aşağı)", "Bob (up and down)"],
    presetSpin: ["Dönme", "Spin"],
    presetPulse: ["Nabız (büyü-küçül)", "Pulse (grow and shrink)"],
    presetShake: ["Sarsıntı", "Shake"],
    presetFadeOut: ["Solma", "Fade out"],
    presetFlash: ["Kırmızı yanıp sönme", "Red flash"],
    presetFrames: ["Sprite kareleri", "Sprite frames"],
    trackPosition: ["Konum (ofset)", "Position (offset)"],
    trackRotation: ["Dönüş (ofset)", "Rotation (offset)"],
    trackScale: ["Ölçek (çarpan)", "Scale (multiplier)"],
    trackColor: ["Renk", "Color"],
    trackOpacity: ["Saydamlık", "Opacity"],
    trackFrame: ["Sprite karesi", "Sprite frame"],
    animationHint: ["Konum ve dönüş anahtarları nesnenin o anki pozuna eklenir; ölçek anahtarları onu çarpar.", "Position and rotation keys are added to the object's current pose; scale keys multiply it."],
    noClips: ["Henüz klip yok. Hazır bir klip ekleyerek başlayın.", "No clips yet. Start by adding a ready-made clip."],
    hEditAnimation: ["Animasyonu düzenle", "Edit animation"],
    // V3: UI components
    onClick: ["Tıklanınca", "On Click"],
    onClickTarget: ["Hedef nesne", "Target object"],
    onClickMethod: ["Çağrılacak metot", "Method to call"],
    onClickHint: ["Hedefteki script'lerde bu adlı metot çalışır. Kodda button.onClick.AddListener(...) da kullanabilirsiniz.", "The method with this name runs on the target's scripts. You can also use button.onClick.AddListener(...) in code."],
    thisObject: ["(Bu nesne)", "(This object)"],
    hotkey: ["Kısayol tuşu", "Hotkey"],
    interactable: ["Tıklanabilir", "Interactable"],
    size: ["Boyut", "Size"],
    drawOrder: ["Çizim sırası", "Draw order"],
    cornerRadius: ["Köşe yuvarlaklığı", "Corner radius"],
    fullScreen: ["Tam ekran", "Full screen"],
    blocksClicks: ["Tıklamaları engeller", "Blocks clicks"],
    image: ["Görsel", "Image"],
    textColor: ["Yazı rengi", "Text color"],
    fillColor: ["Dolgu rengi", "Fill color"],
    direction: ["Yön", "Direction"],
    showLabel: ["Yüzde göster", "Show percentage"],
    anchor: ["Çapa", "Anchor"],
    offset: ["Ofset", "Offset"],
    spriteSheet: ["Sprite sayfası", "Sprite sheet"],
    spriteFrame: ["Kare", "Frame"],
    // V3: scene environment
    environment: ["Ortam", "Environment"],
    fogMode: ["Sis türü", "Fog mode"],
    fogLinear: ["Doğrusal", "Linear"],
    fogExponential: ["Üstel", "Exponential"],
    fogDensity: ["Sis yoğunluğu", "Fog density"],
    screenEffects: ["Ekran efektleri", "Screen effects"],
    bloom: ["Parlama (bloom)", "Bloom"],
    bloomIntensity: ["Parlama gücü", "Bloom intensity"],
    bloomThreshold: ["Parlama eşiği", "Bloom threshold"],
    bloomRadius: ["Parlama yarıçapı", "Bloom radius"],
    vignette: ["Vinyet", "Vignette"],
    vignetteIntensity: ["Vinyet gücü", "Vignette intensity"],
    exposure: ["Pozlama", "Exposure"],
    // V4: input actions
    inputSettings: ["Girdi", "Input"],
    inputHint: ["Betikler eylemleri adıyla okur: Input.GetButtonDown(\"Jump\"), Input.GetAxis(\"Horizontal\"). Klavye, fare, gamepad ve dokunmatik düğmeler aynı anda çalışır.", "Scripts read actions by name: Input.GetButtonDown(\"Jump\"), Input.GetAxis(\"Horizontal\"). Keyboard, mouse, gamepad and touch buttons all work at once."],
    inputActions: ["Eylemler", "Actions"],
    deadZone: ["Çubuk ölü bölgesi", "Stick dead zone"],
    actionKind: ["Tür", "Kind"],
    kindButton: ["Düğme", "Button"],
    kindAxis: ["Eksen", "Axis"],
    keys: ["Tuşlar", "Keys"],
    positiveKeys: ["Artı tuşlar (+1)", "Positive keys (+1)"],
    negativeKeys: ["Eksi tuşlar (−1)", "Negative keys (−1)"],
    padButtons: ["Gamepad düğmeleri", "Gamepad buttons"],
    padPositive: ["Gamepad artı (+1)", "Gamepad positive (+1)"],
    padNegative: ["Gamepad eksi (−1)", "Gamepad negative (−1)"],
    analogStick: ["Analog çubuk", "Analog stick"],
    invertStick: ["Çubuğu ters çevir", "Invert stick"],
    addBinding: ["Ekle…", "Add…"],
    removeBinding: ["Atamayı kaldır", "Remove binding"],
    notBound: ["Atanmadı", "Not bound"],
    addAction: ["Eylem ekle", "Add action"],
    removeAction: ["Eylemi sil", "Delete action"],
    resetInput: ["Varsayılanlara dön", "Reset to defaults"],
    actionNameInvalid: ["Ad bir harfle başlar; yalnızca harf, rakam, boşluk ve _ içerir (en çok 32 karakter).", "A name starts with a letter and uses only letters, digits, spaces and _ (up to 32 characters)."],
    actionNameTaken: ["Bu adda bir eylem zaten var.", "An action with this name already exists."],
    touchMapsTo: ["Dokunmatik düğmeler ok tuşlarına, Space'e ve LeftControl'e, gamepad'de de d-pad'e, A'ya ve X'e basar.", "Touch buttons press the arrow keys, Space and LeftControl, and the gamepad's d-pad, A and X."],
    // V4: Character Controller 2D and Camera Follow
    ccHint: ["Koşma, zıplama, eğimler ve hareketli platformlar hazır. Yön ve zıplama Girdi eylemlerinden okunur; zıplayınca OnJump(), yere inince OnLand(float hız) çağrılır.", "Running, jumping, slopes and moving platforms are built in. Direction and jump come from the input actions; OnJump() runs on a jump and OnLand(float speed) on landing."],
    ccNeedsBody: ["Bu bileşen aynı nesnede Dynamic bir Rigidbody 2D ve bir Collider 2D ister.", "This component needs a Dynamic Rigidbody 2D and a Collider 2D on the same object."],
    ccFix: ["Rigidbody 2D ve Collider 2D ekle", "Add Rigidbody 2D and Collider 2D"],
    ccFixShort: ["Ekle", "Add"],
    ccOnly2D: ["Character Controller 2D yalnızca 2D projelerde çalışır.", "Character Controller 2D only works in 2D projects."],
    ccJumping: ["Zıplama", "Jumping"],
    ccMaxJumps: ["2 yaparsan havada bir kez daha zıplanır (çift zıplama).", "Set it to 2 for one more jump in the air (double jump)."],
    ccCoyote: ["Kenardan düştükten sonra zıplamanın hâlâ çalıştığı süre (saniye).", "Seconds after walking off a ledge during which a jump still works."],
    ccBuffer: ["Yere inmeden hemen önce basılan zıplamanın hatırlandığı süre (saniye).", "Seconds a jump pressed just before landing is remembered."],
    ccVariable: ["Tuşu erken bırakınca zıplama kısalır.", "Letting go of the button early makes the jump shorter."],
    ccSlope: ["Hâlâ zemin sayılan en dik eğim (derece).", "Steepest slope that still counts as ground (degrees)."],
    ccUseInput: ["Kapalıyken betik Move(yön), Jump() ve CancelJump() ile yönetir.", "When off, a script drives it with Move(direction), Jump() and CancelJump()."],
    ccScripted: ["Betikten: GetComponent<CharacterController2D>().Move(1f); Jump(); CancelJump();", "From a script: GetComponent<CharacterController2D>().Move(1f); Jump(); CancelJump();"],
    followHint: ["Kamera hedefi yumuşakça izler. Ekran sarsıntısı için betikte Camera.Shake(0.3f, 0.25f) yazın.", "The camera follows its target smoothly. For screen shake, call Camera.Shake(0.3f, 0.25f) in a script."],
    followNeedsCamera: ["Camera Follow'u Camera bileşeni olan nesneye ekleyin.", "Add Camera Follow to the object that has the Camera component."],
    followPlayerTag: ["(\"Player\" etiketli nesne)", "(Object tagged \"Player\")"],
    followSmooth: ["Kameranın hedefe yetişme süresi (saniye); 0 hemen yapışır.", "Seconds the camera takes to catch up; 0 sticks to the target."],
    followDeadZone: ["Hedefin kamerayı kımıldatmadan dolaşabildiği kutunun boyutu.", "Size of the box the target can move in without moving the camera."],
    followLookAhead: ["Kameranın hareket yönünde öne kaydığı mesafe.", "How far the camera leads in the direction of movement."],
    followBounds: ["Görüntüyü bu dikdörtgenin içinde tutar.", "Keeps the view inside this rectangle."],
    // V4: Nav Agent 2D
    navHint: ["Duvarların (statik collider'lar ve katı karolar) etrafından dolaşarak hedefe yürür. Betikte: agent.SetDestination(nokta); varınca OnDestinationReached() çağrılır.", "Walks to its destination around walls (static colliders and solid tiles). In a script: agent.SetDestination(point); OnDestinationReached() runs on arrival."],
    navOnly2D: ["Nav Agent 2D engellerin etrafından yalnızca 2D projelerde dolaşır.", "Nav Agent 2D only steers around obstacles in 2D projects."],
    navTarget: ["Seçilen nesneyi sürekli kovalar; boşsa SetDestination() ile verilen noktaya gider.", "Keeps chasing the chosen object; when empty it goes where SetDestination() says."],
    navNoTarget: ["(Yok — SetDestination)", "(None — SetDestination)"],
    navRadius: ["Duvarlardan uzak durulan mesafe (ajanın yarı genişliği).", "How far it keeps from walls (half the agent's width)."],
    navRepath: ["Hareket eden bir hedef kovalanırken yeni yol hesaplama aralığı (saniye).", "Seconds between new paths while chasing a moving target."],
    navShowPath: ["Oynarken yolu çizgiyle gösterir (öğrenmek ve hata ayıklamak için).", "Draws the path while playing (for learning and debugging)."],
    // V4: joints
    jointDistanceHint: ["İki nesneyi sabit bir uzaklıkta tutar; \"Max Distance Only\" açıkken ip gibi yalnızca gerilir.", "Keeps two objects at a fixed distance; with \"Max Distance Only\" it only goes taut, like a rope."],
    jointSpringHint: ["Nesneyi yay gibi geri çeker. Frekans sertliği, sönüm zıplamayı belirler.", "Pulls the object back like a spring. Frequency sets the stiffness, damping the bounce."],
    jointNeedsBody: ["Eklemin bir şeyi hareket ettirebilmesi için bu nesnede ya da bağlı nesnede Dynamic bir Rigidbody olmalı.", "For the joint to move anything, this object or the connected one needs a Dynamic Rigidbody."],
    jointConnected: ["Bağlanılan nesne; boşsa dünyadaki bir noktaya bağlanır.", "The object it is tied to; when empty it is tied to a point in the world."],
    jointWorldPoint: ["(Dünyadaki bir nokta)", "(A point in the world)"],
    jointWorldAnchor: ["Dünya noktası", "World point"],
    jointAuto: ["Oyun başladığındaki uzaklığı kullanır.", "Uses the distance at the start of the game."],
    jointRope: ["Yalnızca en uzun mesafeyi korur (ip gibi; yaklaşabilir).", "Only keeps the longest distance (like a rope; the ends may come closer)."],
    jointFrequency: ["Saniyedeki salınım; büyüdükçe yay sertleşir.", "Oscillations per second; higher is stiffer."],
    jointDamping: ["0 uzun süre zıplar, 1 zıplamadan durur.", "0 keeps bouncing, 1 settles without bouncing."],
    // V4: UI Slider, Toggle and Input Field
    uiShowValue: ["Değeri göster", "Show value"],
    uiOnValueChanged: ["Değer değişince", "On value changed"],
    uiOnEndEdit: ["Yazma bitince", "On end edit"],
    uiToggleStyle: ["Görünüm", "Style"],
    uiStyleSwitch: ["Anahtar", "Switch"],
    uiStyleCheckbox: ["Onay kutusu", "Checkbox"],
    uiSliderHint: ["Oyuncu fareyle ya da parmakla sürükler. Betikte: slider.onValueChanged.AddListener(v => { ... });", "The player drags it with the mouse or a finger. In a script: slider.onValueChanged.AddListener(v => { ... });"],
    uiInputHint: ["Oyuncu gerçek bir metin kutusuna yazar (telefonda klavye açılır); yazarken oyun tuşları çalışmaz. Enter yazmayı bitirir.", "The player types in a real text box (phones open their keyboard); game keys pause while typing. Enter finishes editing."],
} as const;

export type TextKey = keyof typeof TEXT;

export function useEngineText() {
    const { tx } = useI18n();
    return useCallback((key: TextKey) => {
        const [tr, en] = TEXT[key];
        return tx({ TR: tr, EN: en });
    }, [tx]);
}

export function engineLocale(language: string) {
    return language === "TR" || language === "AZ" ? "tr" : "en";
}
