"use client";

import { useCallback } from "react";
import { useI18n } from "@/lib/i18n";

/** Engine UI strings: [Türkçe, English]. Other site languages fall back to English. */
const TEXT = {
    back: ["Geri", "Back"],
    hub: ["Projeler", "Projects"],
    save: ["Kaydet", "Save"],
    saving: ["Kaydediliyor…", "Saving…"],
    saved: ["Kaydedildi", "Saved"],
    unsaved: ["Kaydedilmemiş değişiklikler", "Unsaved changes"],
    saveFailed: ["Kaydedilemedi", "Save failed"],
    savedLocal: ["Bu cihaza kaydedildi", "Saved on this device"],
    cloud: ["Bulut", "Cloud"],
    local: ["Yerel", "Local"],
    undo: ["Geri al", "Undo"],
    redo: ["Yinele", "Redo"],
    play: ["Oynat", "Play"],
    pause: ["Duraklat", "Pause"],
    resume: ["Devam", "Resume"],
    step: ["Bir kare ilerle", "Step one frame"],
    stop: ["Durdur", "Stop"],
    restart: ["Yeniden başlat", "Restart"],
    move: ["Taşı (W)", "Move (W)"],
    rotate: ["Döndür (E)", "Rotate (E)"],
    scale: ["Ölçekle (R)", "Scale (R)"],
    worldSpace: ["Dünya ekseni", "World space"],
    localSpace: ["Yerel eksen", "Local space"],
    settings: ["Ayarlar", "Settings"],
    export: ["Dışa aktar", "Export"],
    exportJson: ["Proje dosyası (.json)", "Project file (.json)"],
    exportHtml: ["Oynanabilir HTML oyunu", "Playable HTML game"],
    importProject: ["Proje içe aktar", "Import project"],
    publish: ["Arcade'de yayınla", "Publish to Arcade"],
    publishShort: ["Yayınla", "Publish"],
    published: ["Yayında", "Published"],
    docs: ["Belgeler", "Docs"],
    scene: ["Sahne", "Scene"],
    game: ["Oyun", "Game"],
    hierarchy: ["Hiyerarşi", "Hierarchy"],
    scenes: ["Sahneler", "Scenes"],
    inspector: ["Inspector", "Inspector"],
    project: ["Proje", "Project"],
    console: ["Konsol", "Console"],
    search: ["Ara…", "Search…"],
    create: ["Oluştur", "Create"],
    createChild: ["Alt nesne oluştur", "Create child"],
    duplicate: ["Çoğalt (Ctrl+D)", "Duplicate (Ctrl+D)"],
    rename: ["Yeniden adlandır (F2)", "Rename (F2)"],
    delete: ["Sil (Del)", "Delete (Del)"],
    copy: ["Kopyala (Ctrl+C)", "Copy (Ctrl+C)"],
    paste: ["Yapıştır (Ctrl+V)", "Paste (Ctrl+V)"],
    makePrefab: ["Prefab oluştur", "Create prefab"],
    applyPrefab: ["Prefab'ı güncelle", "Apply to prefab"],
    focus: ["Odakla (F)", "Focus (F)"],
    unparent: ["Kök nesne yap", "Move to root"],
    emptyObject: ["Boş Nesne", "Empty Object"],
    noSelection: ["Düzenlemek için sahneden veya hiyerarşiden bir nesne seçin.", "Select an object in the scene or hierarchy to edit it."],
    multiSelection: ["nesne seçildi", "objects selected"],
    addComponent: ["Bileşen ekle", "Add component"],
    addScript: ["Script ekle", "Add script"],
    newScript: ["Yeni script", "New script"],
    removeComponent: ["Bileşeni kaldır", "Remove component"],
    moveUp: ["Yukarı taşı", "Move up"],
    moveDown: ["Aşağı taşı", "Move down"],
    resetComponent: ["Sıfırla", "Reset"],
    active: ["Aktif", "Active"],
    name: ["Ad", "Name"],
    tag: ["Etiket", "Tag"],
    position: ["Konum", "Position"],
    rotation: ["Dönüş", "Rotation"],
    scaleLabel: ["Ölçek", "Scale"],
    none: ["(Yok)", "(None)"],
    missing: ["(Eksik)", "(Missing)"],
    scripts: ["Scriptler", "Scripts"],
    prefabs: ["Prefab'lar", "Prefabs"],
    textures: ["Dokular", "Textures"],
    uploadTexture: ["Görsel yükle", "Upload image"],
    newScene: ["Yeni sahne", "New scene"],
    startScene: ["Başlangıç sahnesi", "Start scene"],
    setStartScene: ["Başlangıç sahnesi yap", "Set as start scene"],
    openScript: ["Kodu aç", "Open code"],
    instantiate: ["Sahneye ekle", "Add to scene"],
    clear: ["Temizle", "Clear"],
    collapse: ["Birleştir", "Collapse"],
    errors: ["Hatalar", "Errors"],
    warnings: ["Uyarılar", "Warnings"],
    messages: ["Mesajlar", "Messages"],
    consoleEmpty: ["Konsol boş. Debug.Log çıktıları ve hatalar burada görünür.", "The console is empty. Debug.Log output and errors appear here."],
    compileErrors: ["Derleme hataları var", "There are compile errors"],
    compiledOk: ["Tüm scriptler derlendi", "All scripts compiled"],
    playBlocked: ["Oyunu başlatmadan önce derleme hatalarını düzeltin.", "Fix compile errors before playing."],
    playingNote: ["Oyun çalışıyor — düzenleme için durdurun.", "The game is running — stop it to edit."],
    grid: ["Izgara", "Grid"],
    colliders: ["Çarpıştırıcılar", "Colliders"],
    icons: ["Simgeler", "Icons"],
    resetView: ["Görünümü sıfırla", "Reset view"],
    confirmDelete: ["Silinsin mi?", "Delete?"],
    confirmDeleteScript: ["Bu script silinsin mi? Onu kullanan bileşenler de kaldırılacak.", "Delete this script? Components using it will be removed too."],
    confirmDeleteProject: ["Bu proje kalıcı olarak silinsin mi?", "Delete this project permanently?"],
    projectSettings: ["Proje ayarları", "Project settings"],
    sceneSettings: ["Sahne ayarları", "Scene settings"],
    close: ["Kapat", "Close"],
    cancel: ["İptal", "Cancel"],
    ok: ["Tamam", "OK"],
    templates: ["Şablonlar", "Templates"],
    newProject: ["Yeni proje", "New project"],
    myProjects: ["Projelerim", "My projects"],
    open: ["Aç", "Open"],
    loading: ["Yükleniyor…", "Loading…"],
    projectName: ["Proje adı", "Project name"],
    createProject: ["Projeyi oluştur", "Create project"],
    signInForCloud: ["Projelerin buluta kaydedilmesi için giriş yapın. Giriş yapmadan oluşturulan projeler bu tarayıcıda saklanır.", "Sign in to save projects to the cloud. Projects created as a guest are stored in this browser."],
    noProjects: ["Henüz proje yok. Bir şablonla başlayın!", "No projects yet. Start from a template!"],
    lastEdited: ["Son düzenleme", "Last edited"],
    objects: ["nesne", "objects"],
    publishTitle: ["Başlık", "Title"],
    publishDescription: ["Açıklama", "Description"],
    publishNow: ["Yayınla", "Publish"],
    updatePublished: ["Yayını güncelle", "Update listing"],
    unpublish: ["Yayından kaldır", "Unpublish"],
    publishedAt: ["Arcade'de yayında", "Live on the Arcade"],
    publishNeedsCloud: ["Arcade'de yayınlamak için giriş yapıp projeyi buluta kaydedin.", "Sign in and save the project to the cloud to publish it."],
    viewInArcade: ["Arcade'de aç", "Open in Arcade"],
    fps: ["FPS göster", "Show FPS"],
    shadows: ["Gölgeler", "Shadows"],
    antialias: ["Kenar yumuşatma", "Antialiasing"],
    pixelArt: ["Piksel sanat modu", "Pixel art mode"],
    touchControls: ["Dokunmatik kontroller", "Touch controls"],
    aspect: ["En-boy oranı", "Aspect ratio"],
    background: ["Arka plan", "Background"],
    solid: ["Düz renk", "Solid"],
    gradient: ["Gradyan", "Gradient"],
    topColor: ["Üst renk", "Top color"],
    bottomColor: ["Alt renk", "Bottom color"],
    ambient: ["Ortam ışığı", "Ambient light"],
    fog: ["Sis", "Fog"],
    gravity: ["Yerçekimi", "Gravity"],
    fixedStep: ["Fizik adımı (sn)", "Physics step (s)"],
    description: ["Açıklama", "Description"],
    shortcuts: ["Kısayollar", "Shortcuts"],
    apply: ["Uygula", "Apply"],
    compile: ["Derle", "Compile"],
    line: ["satır", "line"],
    scriptFields: ["Inspector alanları", "Inspector fields"],
    noFields: ["Bu script'te public alan yok.", "This script has no public fields."],
    classNotFound: ["Script'te MonoBehaviour sınıfı bulunamadı.", "No MonoBehaviour class found in the script."],
    fitCollider: ["Görsele sığdır", "Fit to visual"],
    previewSound: ["Sesi dinle", "Preview sound"],
    dropHere: ["Sahneye eklemek için bırakın", "Drop to add to the scene"],
    readOnlyPlaying: ["Oynatma modunda düzenleme kapalı", "Editing is disabled in play mode"],
    unsavedLeave: ["Kaydedilmemiş değişiklikler var. Çıkmak istiyor musunuz?", "You have unsaved changes. Leave anyway?"],
    welcomeTitle: ["Hanogt Engine'e hoş geldin", "Welcome to Hanogt Engine"],
    welcomeText: ["Unity benzeri, tarayıcıda çalışan 2D/3D oyun motoru. C# veya C++ ile script yaz, anında oyna, Arcade'de paylaş.", "A Unity-like 2D/3D game engine in your browser. Script in C# or C++, play instantly and share on the Arcade."],
    arcade: ["Arcade", "Arcade"],
    guide: ["Kılavuz", "Guide"],
    rename2: ["Yeniden adlandır", "Rename"],
    deleteLabel: ["Sil", "Delete"],
    duplicateLabel: ["Çoğalt", "Duplicate"],
    thumbnail: ["Kapak görseli", "Thumbnail"],
    captureThumbnail: ["Sahneden yakala", "Capture from scene"],
    guest: ["Misafir", "Guest"],
} as const;

export type TextKey = keyof typeof TEXT;

export function useEngineText() {
    const { language } = useI18n();
    const index = language === "TR" || language === "AZ" ? 0 : 1;
    return useCallback((key: TextKey) => TEXT[key][index], [index]);
}

export function engineLocale(language: string) {
    return language === "TR" || language === "AZ" ? "tr" : "en";
}
