"use client";

import { useCallback } from "react";
import { useI18n } from "@/lib/i18n";

/** Engine UI strings: [Türkçe, English]. Other site languages fall back to English. */
const TEXT = {
    back: ["Geri", "Back"],
    hub: ["Projeler", "Projects"],
    save: ["Kaydet", "Save"],
    saving: ["Kaydediliyor…", "Saving…"],
    saved: ["Kaydedildi", "Saved"],
    unsaved: ["Kaydedilmemiş değişiklikler", "Unsaved changes"],
    saveFailed: ["Kaydedilemedi", "Save failed"],
    savedLocal: ["Bu cihaza kaydedildi", "Saved on this device"],
    cloud: ["Bulut", "Cloud"],
    local: ["Yerel", "Local"],
    undo: ["Geri al", "Undo"],
    redo: ["Yinele", "Redo"],
    play: ["Oynat", "Play"],
    pause: ["Duraklat", "Pause"],
    resume: ["Devam", "Resume"],
    step: ["Bir kare ilerle", "Step one frame"],
    stop: ["Durdur", "Stop"],
    restart: ["Yeniden başlat", "Restart"],
    move: ["Taşı (W)", "Move (W)"],
    rotate: ["Döndür (E)", "Rotate (E)"],
    scale: ["Ölçekle (R)", "Scale (R)"],
    worldSpace: ["Dünya ekseni", "World space"],
    localSpace: ["Yerel eksen", "Local space"],
    settings: ["Ayarlar", "Settings"],
    export: ["Dışa aktar", "Export"],
    exportJson: ["Proje dosyası (.json)", "Project file (.json)"],
    exportHtml: ["Oynanabilir HTML oyunu", "Playable HTML game"],
    importProject: ["Proje içe aktar", "Import project"],
    publish: ["Arcade'de yayınla", "Publish to Arcade"],
    publishShort: ["Yayınla", "Publish"],
    published: ["Yayında", "Published"],
    docs: ["Belgeler", "Docs"],
    scene: ["Sahne", "Scene"],
    game: ["Oyun", "Game"],
    hierarchy: ["Hiyerarşi", "Hierarchy"],
    scenes: ["Sahneler", "Scenes"],
    inspector: ["Inspector", "Inspector"],
    project: ["Proje", "Project"],
    console: ["Konsol", "Console"],
    search: ["Ara…", "Search…"],
    create: ["Oluştur", "Create"],
    createChild: ["Alt nesne oluştur", "Create child"],
    duplicate: ["Çoğalt (Ctrl+D)", "Duplicate (Ctrl+D)"],
    rename: ["Yeniden adlandır (F2)", "Rename (F2)"],
    delete: ["Sil (Del)", "Delete (Del)"],
    copy: ["Kopyala (Ctrl+C)", "Copy (Ctrl+C)"],
    paste: ["Yapıştır (Ctrl+V)", "Paste (Ctrl+V)"],
    makePrefab: ["Prefab oluştur", "Create prefab"],
    applyPrefab: ["Prefab'ı güncelle", "Apply to prefab"],
    focus: ["Odakla (F)", "Focus (F)"],
    unparent: ["Kök nesne yap", "Move to root"],
    emptyObject: ["Boş Nesne", "Empty Object"],
    noSelection: ["Düzenlemek için sahneden veya hiyerarşiden bir nesne seçin.", "Select an object in the scene or hierarchy to edit it."],
    multiSelection: ["nesne seçildi", "objects selected"],
    addComponent: ["Bileşen ekle", "Add component"],
    addScript: ["Script ekle", "Add script"],
    newScript: ["Yeni script", "New script"],
    removeComponent: ["Bileşeni kaldır", "Remove component"],
    moveUp: ["Yukarı taşı", "Move up"],
    moveDown: ["Aşağı taşı", "Move down"],
    resetComponent: ["Sıfırla", "Reset"],
    active: ["Aktif", "Active"],
    name: ["Ad", "Name"],
    tag: ["Etiket", "Tag"],
    position: ["Konum", "Position"],
    rotation: ["Dönüş", "Rotation"],
    scaleLabel: ["Ölçek", "Scale"],
    none: ["(Yok)", "(None)"],
    missing: ["(Eksik)", "(Missing)"],
    scripts: ["Scriptler", "Scripts"],
    prefabs: ["Prefab'lar", "Prefabs"],
    textures: ["Dokular", "Textures"],
    uploadTexture: ["Görsel yükle", "Upload image"],
    newScene: ["Yeni sahne", "New scene"],
    startScene: ["Başlangıç sahnesi", "Start scene"],
    setStartScene: ["Başlangıç sahnesi yap", "Set as start scene"],
    openScript: ["Kodu aç", "Open code"],
    instantiate: ["Sahneye ekle", "Add to scene"],
    clear: ["Temizle", "Clear"],
    collapse: ["Birleştir", "Collapse"],
    errors: ["Hatalar", "Errors"],
    warnings: ["Uyarılar", "Warnings"],
    messages: ["Mesajlar", "Messages"],
    consoleEmpty: ["Konsol boş. Debug.Log çıktıları ve hatalar burada görünür.", "The console is empty. Debug.Log output and errors appear here."],
    compileErrors: ["Derleme hataları var", "There are compile errors"],
    compiledOk: ["Tüm scriptler derlendi", "All scripts compiled"],
    playBlocked: ["Oyunu başlatmadan önce derleme hatalarını düzeltin.", "Fix compile errors before playing."],
    playingNote: ["Oyun çalışıyor — düzenleme için durdurun.", "The game is running — stop it to edit."],
    grid: ["Izgara", "Grid"],
    colliders: ["Çarpıştırıcılar", "Colliders"],
    icons: ["Simgeler", "Icons"],
    resetView: ["Görünümü sıfırla", "Reset view"],
    confirmDelete: ["Silinsin mi?", "Delete?"],
    confirmDeleteScript: ["Bu script silinsin mi? Onu kullanan bileşenler de kaldırılacak.", "Delete this script? Components using it will be removed too."],
    confirmDeleteProject: ["Bu proje kalıcı olarak silinsin mi?", "Delete this project permanently?"],
    projectSettings: ["Proje ayarları", "Project settings"],
    sceneSettings: ["Sahne ayarları", "Scene settings"],
    close: ["Kapat", "Close"],
    cancel: ["İptal", "Cancel"],
    ok: ["Tamam", "OK"],
    templates: ["Şablonlar", "Templates"],
    newProject: ["Yeni proje", "New project"],
    myProjects: ["Projelerim", "My projects"],
    open: ["Aç", "Open"],
    loading: ["Yükleniyor…", "Loading…"],
    projectName: ["Proje adı", "Project name"],
    createProject: ["Projeyi oluştur", "Create project"],
    signInForCloud: ["Projelerin buluta kaydedilmesi için giriş yapın. Giriş yapmadan oluşturulan projeler bu tarayıcıda saklanır.", "Sign in to save projects to the cloud. Projects created as a guest are stored in this browser."],
    noProjects: ["Henüz proje yok. Bir şablonla başlayın!", "No projects yet. Start from a template!"],
    lastEdited: ["Son düzenleme", "Last edited"],
    objects: ["nesne", "objects"],
    publishTitle: ["Başlık", "Title"],
    publishDescription: ["Açıklama", "Description"],
    publishNow: ["Yayınla", "Publish"],
    updatePublished: ["Yayını güncelle", "Update listing"],
    unpublish: ["Yayından kaldır", "Unpublish"],
    publishedAt: ["Arcade'de yayında", "Live on the Arcade"],
    publishNeedsCloud: ["Arcade'de yayınlamak için giriş yapıp projeyi buluta kaydedin.", "Sign in and save the project to the cloud to publish it."],
    viewInArcade: ["Arcade'de aç", "Open in Arcade"],
    fps: ["FPS göster", "Show FPS"],
    shadows: ["Gölgeler", "Shadows"],
    antialias: ["Kenar yumuşatma", "Antialiasing"],
    pixelArt: ["Piksel sanat modu", "Pixel art mode"],
    touchControls: ["Dokunmatik kontroller", "Touch controls"],
    aspect: ["En-boy oranı", "Aspect ratio"],
    background: ["Arka plan", "Background"],
    solid: ["Düz renk", "Solid"],
    gradient: ["Gradyan", "Gradient"],
    topColor: ["Üst renk", "Top color"],
    bottomColor: ["Alt renk", "Bottom color"],
    ambient: ["Ortam ışığı", "Ambient light"],
    fog: ["Sis", "Fog"],
    gravity: ["Yerçekimi", "Gravity"],
    fixedStep: ["Fizik adımı (sn)", "Physics step (s)"],
    description: ["Açıklama", "Description"],
    shortcuts: ["Kısayollar", "Shortcuts"],
    apply: ["Uygula", "Apply"],
    compile: ["Derle", "Compile"],
    line: ["satır", "line"],
    scriptFields: ["Inspector alanları", "Inspector fields"],
    noFields: ["Bu script'te public alan yok.", "This script has no public fields."],
    classNotFound: ["Script'te MonoBehaviour sınıfı bulunamadı.", "No MonoBehaviour class found in the script."],
    fitCollider: ["Görsele sığdır", "Fit to visual"],
    previewSound: ["Sesi dinle", "Preview sound"],
    dropHere: ["Sahneye eklemek için bırakın", "Drop to add to the scene"],
    readOnlyPlaying: ["Oynatma modunda düzenleme kapalı", "Editing is disabled in play mode"],
    unsavedLeave: ["Kaydedilmemiş değişiklikler var. Çıkmak istiyor musunuz?", "You have unsaved changes. Leave anyway?"],
    welcomeTitle: ["Hanogt Engine'e hoş geldin", "Welcome to Hanogt Engine"],
    welcomeText: ["Unity benzeri, tarayıcıda çalışan 2D/3D oyun motoru. C# veya C++ ile script yaz, anında oyna, Arcade'de paylaş.", "A Unity-like 2D/3D game engine in your browser. Script in C# or C++, play instantly and share on the Arcade."],
    arcade: ["Arcade", "Arcade"],
    guide: ["Kılavuz", "Guide"],
    rename2: ["Yeniden adlandır", "Rename"],
    deleteLabel: ["Sil", "Delete"],
    duplicateLabel: ["Çoğalt", "Duplicate"],
    thumbnail: ["Kapak görseli", "Thumbnail"],
    captureThumbnail: ["Sahneden yakala", "Capture from scene"],
    guest: ["Misafir", "Guest"],
    hCreateEntity: ["Nesne oluştur", "Create object"],
    hHideEntity: ["Nesneyi gizle", "Hide object"],
    hShowEntity: ["Nesneyi göster", "Show object"],
    hReparent: ["Hiyerarşiyi düzenle", "Edit hierarchy"],
    hUnparent: ["Kök nesne yap", "Move to root"],
    hEditScript: ["Script düzenle", "Edit script"],
    hPaste: ["Yapıştır", "Paste"],
    hImportProject: ["Proje içe aktar", "Import project"],
    hUploadTexture: ["Doku yükle", "Upload texture"],
    hOpenScene: ["Sahne aç", "Open scene"],
    hTransform: ["Dönüşüm", "Transform"],
    hCreateSprite: ["Sprite oluştur", "Create sprite"],
    hComponentEnabled: ["Bileşen etkinliği", "Toggle component"],
    hResetComponent: ["Bileşeni sıfırla", "Reset component"],
    hMoveComponent: ["Bileşeni taşı", "Move component"],
    hRemoveComponent: ["Bileşeni kaldır", "Remove component"],
    hScriptName: ["Script adı", "Script name"],
    hPrefabName: ["Prefab adı", "Prefab name"],
    hTextureName: ["Doku adı", "Texture name"],
    hSceneName: ["Sahne adı", "Scene name"],
    hStartScene: ["Başlangıç sahnesi", "Start scene"],
    hEditComponent: ["Bileşeni düzenle", "Edit component"],
    hFitCollider: ["Çarpıştırıcıyı sığdır", "Fit collider"],
    toggleExpand: ["Aç/kapat", "Expand/collapse"],
    hide: ["Gizle", "Hide"],
    show: ["Göster", "Show"],
    selectScript: ["Script seçin", "Select a script"],
    saveConflict: ["Proje başka bir sekmede/cihazda değişti. Sayfayı yenileyip güncel sürümü yükleyin; bu sekmedeki değişiklikleri kaybetmemek için önce JSON olarak dışa aktarabilirsiniz.", "This project changed in another tab or on another device. Reload to get the latest version; export it as JSON first to keep the changes made in this tab."],
    clipboardFailed: ["Pano içeriği okunamadı.", "Couldn't read the clipboard."],
    htmlExported: ["Oynanabilir HTML dosyası indirildi.", "Playable HTML file downloaded."],
    exportFailed: ["Dışa aktarılamadı.", "Export failed."],
    importConfirm: ["\"{name}\" içe aktarılsın mı? Bu projenin içeriği değiştirilecek (geri alınabilir).", "Import \"{name}\"? This project's content will be replaced (you can undo it)."],
    imported: ["Proje içe aktarıldı.", "Project imported."],
    importFailed: ["İçe aktarılamadı.", "Import failed."],
    unmute: ["Sesi aç", "Unmute"],
    mute: ["Sesi kapat", "Mute"],
    editorPanels: ["Editör panelleri", "Editor panels"],
    codeTabs: ["Kod", "Code"],
    textureUploaded: ["\"{name}\" yüklendi ({size}).", "\"{name}\" uploaded ({size})."],
    imageUploadFailed: ["Görsel yüklenemedi.", "The image couldn't be uploaded."],
    noScriptsYet: ["Henüz script yok — C# veya C++ ile başlayın.", "No scripts yet — start with C# or C++."],
    prefabHint: ["Hiyerarşide bir nesneye sağ tıklayıp “{action}” seçin.", "Right-click an object in the Hierarchy and choose “{action}”."],
    texturesHint: ["PNG/JPG/WEBP yükleyip sprite veya materyallerde kullanın. Sahneye sürükleyebilirsiniz.", "Upload PNG/JPG/WEBP images to use in sprites or materials. You can drag them into the scene."],
    webglFailed: ["WebGL başlatılamadı. Tarayıcınızın donanım hızlandırmasını açın.", "WebGL couldn't start. Turn on hardware acceleration in your browser."],
    sceneHelp2D: ["Sol tık: seç · Sürükle: kaydır · Tekerlek: yakınlaş · F: odakla", "Left click: select · Drag: pan · Wheel: zoom · F: focus"],
    sceneHelp3D: ["Sol tık: seç · Sol sürükle: döndür · Sağ sürükle: kaydır · Tekerlek: yakınlaş · F: odakla", "Left click: select · Left drag: orbit · Right drag: pan · Wheel: zoom · F: focus"],
    componentMenu: ["Bileşen menüsü", "Component menu"],
    prefabUsage1: ["Script'lerde ", "Assign this prefab to a "],
    prefabUsage2: [" alanına bu prefab'ı atayıp ", " field in a script and spawn copies in the game with "],
    prefabUsage3: [" ile oyunda çoğaltabilirsiniz.", "."],
    sceneSetting: ["Sahne ayarı", "Scene setting"],
    compileErrorsFirst: ["{count} derleme hatası — ilk: satır {line}: {message}", "{count} compile errors — first: line {line}: {message}"],
    publishFailed: ["Yayınlanamadı.", "Publishing failed."],
    actionFailed: ["İşlem başarısız.", "Action failed."],
    publishNotice: ["Yayınlanan oyunlar Arcade'de herkese açık görünür; kodunuz oyunu çalıştırmak için oyuncuların tarayıcısına gönderilir. Kişisel veri, parola veya gizli anahtar paylaşmayın. Kullanım şartlarına aykırı içerik kaldırılır.", "Published games are public on the Arcade, and your code is sent to players' browsers to run the game. Don't share personal data, passwords or secret keys. Content that breaks the Terms of Use is removed."],
    editorOrigin: ["Editör", "Editor"],
    frame: ["kare", "frame"],
    cloudLoadFailed: ["Bulut projeleri yüklenemedi.", "Cloud projects couldn't be loaded."],
    createFailed: ["Proje oluşturulamadı.", "The project couldn't be created."],
    downloadFailed: ["İndirilemedi.", "Download failed."],
    signIn: ["Giriş yap", "Sign in"],
    savesToCloud: ["Proje hesabınıza (bulut) kaydedilecek.", "The project will be saved to your account (cloud)."],
    savesToBrowser: ["Proje bu tarayıcıya kaydedilecek.", "The project will be saved in this browser."],
    engineLoading: ["Hanogt Engine yükleniyor…", "Loading Hanogt Engine…"],
    projectNotInBrowser: ["Bu proje bu tarayıcıda bulunamadı. Başka bir cihazda veya tarayıcıda oluşturulmuş olabilir.", "This project isn't stored in this browser. It may have been created on another device or browser."],
    signInForCloudProjects: ["Bulut projelerini açmak için giriş yapmalısınız.", "Sign in to open cloud projects."],
    projectLoadFailed: ["Proje yüklenemedi.", "The project couldn't be loaded."],
    projectOpenFailed: ["Proje açılamadı", "Couldn't open the project"],
    projectLoading: ["Proje yükleniyor…", "Loading project…"],
    retry: ["Tekrar dene", "Try again"],
} as const;

export type TextKey = keyof typeof TEXT;

export function useEngineText() {
    const { language } = useI18n();
    const index = language === "TR" || language === "AZ" ? 0 : 1;
    return useCallback((key: TextKey) => TEXT[key][index], [index]);
}

export function engineLocale(language: string) {
    return language === "TR" || language === "AZ" ? "tr" : "en";
}
