import type { Copy } from "@/lib/i18n";
import type { PaddleEnvironment, PaddleStatus } from "@/lib/paddle";
import {
    MAX_ACTIVE_ANNOUNCEMENTS,
    type AdminAuditAction,
    type AnnouncementLevel,
    type FeedbackStatus,
    type ReportCategory,
    type SecurityRisk,
    type UserRole,
} from "./types";

/** Translated messages for the `code` field of admin API errors. */
export const ERROR_COPY: Record<string, Copy> = {
    not_found: { TR: "Kayıt bulunamadı ya da bu işlem için yetkiniz yok.", EN: "Not found, or you don't have access to this action." },
    forbidden: { TR: "Rolünüz bu işleme izin vermiyor.", EN: "Your role doesn't allow this action." },
    bad_origin: { TR: "İstek güvenlik denetiminden geçemedi. Sayfayı yenileyip tekrar deneyin.", EN: "The request failed a security check. Reload the page and try again." },
    rate_limited: { TR: "Çok fazla istek gönderildi. Biraz bekleyip tekrar deneyin.", EN: "Too many requests. Wait a moment and try again." },
    unsupported_media_type: { TR: "İstek biçimi geçersiz. Sayfayı yenileyin.", EN: "Invalid request format. Reload the page." },
    payload_too_large: { TR: "Gönderilen içerik çok büyük.", EN: "The submitted content is too large." },
    invalid_json: { TR: "İstek okunamadı. Sayfayı yenileyip tekrar deneyin.", EN: "The request couldn't be read. Reload the page and try again." },
    unknown_field: { TR: "İstek beklenmeyen bir alan içeriyor. Sayfayı yenileyin.", EN: "The request contains an unexpected field. Reload the page." },
    invalid_action: { TR: "Geçersiz işlem.", EN: "Invalid action." },
    invalid_id: { TR: "Kayıt kimliği geçersiz.", EN: "Invalid record id." },
    invalid_email: { TR: "Geçerli bir e-posta adresi girin.", EN: "Enter a valid e-mail address." },
    invalid_role: { TR: "Geçersiz rol.", EN: "Invalid role." },
    invalid_status: { TR: "Geçersiz durum.", EN: "Invalid status." },
    invalid_text: { TR: "Metin geçersiz.", EN: "The text is invalid." },
    text_required: { TR: "Metin boş olamaz.", EN: "The text can't be empty." },
    too_long: { TR: "Metin izin verilen uzunluğu aşıyor.", EN: "The text is longer than allowed." },
    invalid_level: { TR: "Geçersiz duyuru seviyesi.", EN: "Invalid announcement level." },
    invalid_link: { TR: "Bağlantı / ile başlayan bir yol veya https adresi olmalıdır.", EN: "The link must be a path starting with / or an https URL." },
    invalid_dates: { TR: "Tarihler geçersiz: bitiş, başlangıçtan sonra ve etkin duyurularda gelecekte olmalıdır.", EN: "Invalid dates: the end must follow the start and, for active announcements, lie in the future." },
    invalid_query: { TR: "Arama ifadesi geçersiz.", EN: "Invalid search." },
    invalid_cursor: { TR: "Sayfa bilgisi geçersiz; aramayı yenileyin.", EN: "Invalid page cursor; refresh the search." },
    invalid_boolean: { TR: "Açık/kapalı değeri geçersiz.", EN: "Invalid on/off value." },
    user_not_found: { TR: "Kullanıcı bulunamadı.", EN: "User not found." },
    cannot_target_self: { TR: "Bu işlemi kendi hesabınıza uygulayamazsınız.", EN: "You can't do this to your own account." },
    cannot_modify_owner: { TR: "Sahip hesapları panelden değiştirilemez.", EN: "Owner accounts can't be changed from the panel." },
    insufficient_role: { TR: "Yöneticileri yalnızca sahipler yönetebilir.", EN: "Only owners can manage admins." },
    already_suspended: { TR: "Hesap zaten askıya alınmış.", EN: "The account is already suspended." },
    not_suspended: { TR: "Hesap zaten etkin.", EN: "The account is already active." },
    no_change: { TR: "Değişiklik yok.", EN: "Nothing changed." },
    already_handled: { TR: "Bu kayıt başka bir ekip üyesi tarafından zaten işlendi.", EN: "Another team member already handled this." },
    conflict: { TR: "Kayıt aynı anda değişti. Listeyi yenileyip tekrar deneyin.", EN: "The record changed at the same time. Refresh and try again." },
    confirmation_mismatch: { TR: "Onay metni eşleşmiyor. Silinecek hesabın e-posta adresini aynen yazın.", EN: "The confirmation doesn't match. Type the e-mail address of the account exactly." },
    deploy_failed: { TR: "Kurallar yayımlanamadı. Hizmet hesabının Firebase Rules yetkisini kontrol edin.", EN: "The rules couldn't be deployed. Check that the service account may manage Firebase Rules." },
    too_many_active: {
        TR: "Aynı anda en fazla {count} etkin duyuru olabilir. Önce birini kapatın.",
        EN: "At most {count} announcements can be active at once. Turn one off first.",
        vars: { count: MAX_ACTIVE_ANNOUNCEMENTS },
    },
    invalid_plan: { TR: "Geçersiz plan.", EN: "Invalid plan." },
    invalid_price: { TR: "Fiyat 0 ile 100.000 arasında olmalı.", EN: "The price must be between 0 and 100,000." },
    invalid_number: { TR: "Sayı geçersiz ya da izin verilen aralığın dışında.", EN: "The number is invalid or out of range." },
    invalid_coupon: { TR: "Kupon kodu 3-24 karakter olmalı; yalnızca büyük harf, rakam, - ve _ kullanın.", EN: "Coupon codes are 3-24 characters: capital letters, digits, - and _ only." },
    coupon_exists: { TR: "Bu kupon kodu zaten var.", EN: "That coupon code already exists." },
    paddle_unconfigured: { TR: "Paddle bağlı değil. Önce Paddle anahtarlarını Vercel'e girip yeniden dağıtın.", EN: "Paddle isn't connected. Add the Paddle keys in Vercel and redeploy first." },
    operator_required: { TR: "Satışları herkese açmadan önce İşletme bilgilerini (yasal ad ve iletişim e-postası) doldur; Paddle'ın site incelemesi ve yasal metinler bunu istiyor.", EN: "Fill in the business details (legal name and contact e-mail) before opening sales to everyone; Paddle's website review and the legal texts need them." },
    paddle_error: { TR: "Paddle isteği tamamlanamadı. Biraz sonra tekrar deneyin; sürerse Paddle bağlantısının durumuna bakın.", EN: "The Paddle request failed. Try again shortly; if it keeps failing, check the Paddle connection status." },
    paddle_coupon_code: { TR: "Paddle'a aktarılan kupon kodları yalnızca harf ve rakamdan oluşabilir; - ve _ kullanmayın.", EN: "Coupon codes sent to Paddle may only contain letters and digits; don't use - or _." },
    paddle_coupon_taken: { TR: "Bu kod Paddle'da başka bir indirime ait (silinmiş eski bir kuponun ya da Paddle'da elle oluşturulmuş bir indirimin; arşivlenmiş olsa da). Silinmiş bir kuponunsa aşağıdaki \"Silinen kuponlar\"dan geri yükle; değilse başka bir kod seç.", EN: "This code belongs to another discount in Paddle (a deleted coupon's, or one made in Paddle by hand; archived ones count too). If it was a deleted coupon, restore it from \"Deleted coupons\" below; otherwise pick another code." },
    coupon_restore_expired: { TR: "Bu kuponun bitiş tarihi geçmiş; geri yüklemek için ileri bir tarih seç ya da tarihi boş bırak (süresiz).", EN: "This coupon's end date has passed; pick a later date to restore it, or leave it empty (no end date)." },
    coupon_restore_used_up: { TR: "Bu kuponun kullanım hakkı dolmuş; geri yüklemek için daha yüksek bir kullanım sayısı gir ya da boş bırak (sınırsız).", EN: "This coupon's uses are spent; enter a higher limit to restore it, or leave it empty (unlimited)." },
    invalid_price_id: { TR: "Fiyat kimliği geçersiz. Paddle'daki pri_ ile başlayan kimliği girin.", EN: "Invalid price ID. Enter the ID starting with pri_ from Paddle." },
    price_mismatch: { TR: "Seçilen fiyat bu alana uymuyor: Paddle'da etkin değil, faturalama aralığı farklı ya da aynı fiyat iki kez seçilmiş.", EN: "The chosen price doesn't fit: it isn't active in Paddle, its billing period differs or the same price was chosen twice." },
    already_linked: { TR: "Bu Paddle müşterisi başka bir hesaba bağlı.", EN: "This Paddle customer is linked to another account." },
    unavailable: { TR: "Yönetim hizmetine şu anda ulaşılamıyor.", EN: "The admin service is unavailable right now." },
    network: { TR: "Sunucuya bağlanılamadı. İnternet bağlantınızı kontrol edin.", EN: "Couldn't reach the server. Check your internet connection." },
    unknown: { TR: "Beklenmeyen bir hata oluştu.", EN: "Something unexpected went wrong." },
};

export const RATE_LIMIT_WAIT: Copy = { TR: "Çok fazla istek gönderildi. {seconds} saniye sonra tekrar deneyin.", EN: "Too many requests. Try again in {seconds} seconds." };

export const COMMON = {
    retry: { TR: "Tekrar dene", EN: "Try again" },
    refresh: { TR: "Yenile", EN: "Refresh" },
    cancel: { TR: "Vazgeç", EN: "Cancel" },
    close: { TR: "Kapat", EN: "Close" },
    save: { TR: "Kaydet", EN: "Save" },
    delete: { TR: "Sil", EN: "Delete" },
    loading: { TR: "Yükleniyor…", EN: "Loading…" },
    loadMore: { TR: "Daha fazla yükle", EN: "Load more" },
    optional: { TR: "(isteğe bağlı)", EN: "(optional)" },
    unavailable: { TR: "Alınamadı", EN: "Unavailable" },
    you: { TR: "Siz", EN: "You" },
    all: { TR: "Tümü", EN: "All" },
    search: { TR: "Ara", EN: "Search" },
    noResults: { TR: "Filtrelerle eşleşen kayıt yok.", EN: "No records match the filters." },
    clearFilters: { TR: "Filtreleri temizle", EN: "Clear filters" },
    characters: { TR: "{count}/{max} karakter", EN: "{count}/{max} characters" },
    updatedAgo: { TR: "Güncellendi: {time}", EN: "Updated {time}" },
} satisfies Record<string, Copy>;

export const ROLE_COPY: Record<UserRole, Copy> = {
    owner: { TR: "Sahip", EN: "Owner" },
    admin: { TR: "Yönetici", EN: "Admin" },
    moderator: { TR: "Moderatör", EN: "Moderator" },
    user: { TR: "Kullanıcı", EN: "User" },
};

export const ROLE_DESCRIPTION_COPY: Record<UserRole, Copy> = {
    owner: { TR: "Sitenin kurucusu (yerleşik sahip veya ADMIN_EMAILS); her şeye erişir ve panelden değiştirilemez.", EN: "The site's founder (built-in owner or ADMIN_EMAILS); full access and can't be changed from the panel." },
    admin: { TR: "Moderasyona ek olarak kullanıcıları ve duyuruları yönetir.", EN: "Manages users and announcements in addition to moderation." },
    moderator: { TR: "Bildirimleri, yorumları, Arcade oyunlarını, geri bildirimleri ve destek taleplerini yönetir.", EN: "Handles reports, comments, Arcade games, feedback and support tickets." },
    user: { TR: "Ekip yetkisi yok.", EN: "No staff access." },
};

export const FEEDBACK_STATUS_COPY: Record<FeedbackStatus, Copy> = {
    open: { TR: "Açık", EN: "Open" },
    planned: { TR: "Planlandı", EN: "Planned" },
    "in-progress": { TR: "Üzerinde çalışılıyor", EN: "In progress" },
    done: { TR: "Tamamlandı", EN: "Done" },
    closed: { TR: "Kapatıldı", EN: "Closed" },
};

export const LEVEL_COPY: Record<AnnouncementLevel, Copy> = {
    info: { TR: "Bilgi", EN: "Info" },
    success: { TR: "Başarı", EN: "Success" },
    warning: { TR: "Uyarı", EN: "Warning" },
    danger: { TR: "Kritik", EN: "Critical" },
};

export const CATEGORY_COPY: Record<ReportCategory, Copy> = {
    malware: { TR: "Zararlı kod", EN: "Malware" },
    copyright: { TR: "Telif hakkı", EN: "Copyright" },
    personal_data: { TR: "Kişisel veri", EN: "Personal data" },
    spam: { TR: "Spam", EN: "Spam" },
    other: { TR: "Diğer", EN: "Other" },
};

export const RISK_COPY: Record<SecurityRisk, Copy> = {
    critical: { TR: "Kritik", EN: "Critical" },
    high: { TR: "Yüksek", EN: "High" },
    medium: { TR: "Orta", EN: "Medium" },
    low: { TR: "Düşük", EN: "Low" },
    unknown: { TR: "Bilinmiyor", EN: "Unknown" },
};

export const PADDLE_ENVIRONMENT_COPY: Record<PaddleEnvironment, Copy> = {
    sandbox: { TR: "Sandbox", EN: "Sandbox" },
    production: { TR: "Canlı", EN: "Live" },
};

export const PADDLE_STATUS_COPY: Record<PaddleStatus, Copy> = {
    active: { TR: "Etkin", EN: "Active" },
    trialing: { TR: "Deneme süresinde", EN: "Trialing" },
    past_due: { TR: "Ödeme bekleniyor", EN: "Payment overdue" },
    paused: { TR: "Duraklatıldı", EN: "Paused" },
    canceled: { TR: "İptal edildi", EN: "Canceled" },
};

export const SECURITY_ACTION_COPY: Record<string, Copy> = {
    execution_blocked: { TR: "Kod çalıştırma engellendi", EN: "Code run blocked" },
};

export const AUDIT_ACTION_COPY: Record<AdminAuditAction, Copy> = {
    "user.suspend": { TR: "Hesap askıya alındı", EN: "Account suspended" },
    "user.unsuspend": { TR: "Askı kaldırıldı", EN: "Suspension lifted" },
    "user.set_role": { TR: "Rol değiştirildi", EN: "Role changed" },
    "user.reset_2fa": { TR: "İki adımlı doğrulama sıfırlandı", EN: "Two-step verification reset" },
    "report.resolve": { TR: "Bildirim çözüldü", EN: "Report resolved" },
    "report.dismiss": { TR: "Bildirim reddedildi", EN: "Report dismissed" },
    "report.remove_content": { TR: "İçerik kaldırıldı", EN: "Content removed" },
    "media.cleanup_incomplete": { TR: "Media temizliği yarım kaldı", EN: "Media cleanup incomplete" },
    "news_comment.delete": { TR: "Haber yorumu silindi", EN: "News comment deleted" },
    "arcade.unpublish": { TR: "Oyun yayından kaldırıldı", EN: "Game unpublished" },
    "arcade.feature": { TR: "Oyun öne çıkarıldı", EN: "Game featured" },
    "arcade.unfeature": { TR: "Öne çıkarma kaldırıldı", EN: "Game unfeatured" },
    "feedback.set_status": { TR: "Geri bildirim durumu değişti", EN: "Feedback status changed" },
    "feedback.reply": { TR: "Resmî yanıt gönderildi", EN: "Official reply posted" },
    "feedback.delete": { TR: "Geri bildirim silindi", EN: "Feedback deleted" },
    "announcement.create": { TR: "Duyuru oluşturuldu", EN: "Announcement created" },
    "announcement.update": { TR: "Duyuru güncellendi", EN: "Announcement updated" },
    "announcement.set_active": { TR: "Duyuru açıldı veya kapatıldı", EN: "Announcement switched on or off" },
    "announcement.delete": { TR: "Duyuru silindi", EN: "Announcement deleted" },
    "ticket.reply": { TR: "Destek talebine yanıt verildi", EN: "Support ticket answered" },
    "ticket.set_status": { TR: "Talep durumu değişti", EN: "Ticket status changed" },
    "ticket.set_priority": { TR: "Talep önceliği değişti", EN: "Ticket priority changed" },
    "ticket.delete": { TR: "Destek talebi silindi", EN: "Support ticket deleted" },
    "user.delete_data": { TR: "Kullanıcı verileri silindi", EN: "User data deleted" },
    "cloud.deploy_rules": { TR: "Güvenlik kuralları yayımlandı", EN: "Security rules deployed" },
    "plan.set_price": { TR: "Plan fiyatı değişti", EN: "Plan price changed" },
    "coupon.create": { TR: "Kupon oluşturuldu", EN: "Coupon created" },
    "coupon.set_active": { TR: "Kupon açıldı veya kapatıldı", EN: "Coupon switched on or off" },
    "coupon.delete": { TR: "Kupon silindi", EN: "Coupon deleted" },
    "coupon.sync": { TR: "Kupon Paddle'a aktarıldı", EN: "Coupon sent to Paddle" },
    "coupon.restore": { TR: "Silinen kupon geri yüklendi", EN: "Deleted coupon restored" },
    "feature.set": { TR: "Özelliğin kitlesi değişti", EN: "Feature audience changed" },
    "ai_engine.set": { TR: "Hanogt AI motoru ayarları değişti", EN: "Hanogt AI engine settings changed" },
    "paddle.set_prices": { TR: "Paddle fiyat eşlemesi değişti", EN: "Paddle price mapping changed" },
    "paddle.set_sales_open": { TR: "Satışlar açıldı veya kapatıldı", EN: "Sales opened or closed" },
    "paddle.create_catalog": { TR: "Paddle kataloğu oluşturuldu", EN: "Paddle catalog created" },
    "paddle.fix_quantity": { TR: "Paddle fiyatlarının adedi 1'e sabitlendi", EN: "Paddle prices fixed to a quantity of 1" },
    "paddle.link": { TR: "Paddle aboneliği hesaba bağlandı", EN: "Paddle subscription linked to an account" },
    "paddle.dismiss": { TR: "Eşleşmeyen Paddle aboneliği yoksayıldı", EN: "Unlinked Paddle subscription dismissed" },
    "paddle.resync": { TR: "Abonelik Paddle'dan yeniden eşitlendi", EN: "Subscription re-synced from Paddle" },
    "legal.set_info": { TR: "İşletme bilgileri güncellendi", EN: "Business details updated" },
    "subscription.set_plan": { TR: "Kullanıcının planı değişti", EN: "User's plan changed" },
    "subscription.block": { TR: "Plan kullanımı engellendi", EN: "Plan use blocked" },
    "subscription.unblock": { TR: "Plan engeli kaldırıldı", EN: "Plan block lifted" },
    "subscription.remove": { TR: "Plan kaldırıldı", EN: "Plan removed" },
    "subscription.reset_ai": { TR: "Hanogt AI sınırı sıfırlandı", EN: "Hanogt AI limit reset" },
    "ai_api.revoke_all": { TR: "Hanogt AI API anahtarlarının tümü iptal edildi", EN: "All Hanogt AI API keys revoked" },
    "subscription.grant_ai": { TR: "Ek Hanogt AI hakkı verildi", EN: "Extra Hanogt AI quota granted" },
};

/** Labels for common audit detail keys; other keys are shown as they are. */
export const DETAIL_KEY_COPY: Record<string, Copy> = {
    email: { TR: "E-posta", EN: "E-mail" },
    plan: { TR: "Plan", EN: "Plan" },
    monthly: { TR: "Aylık", EN: "Monthly" },
    yearly: { TR: "Yıllık", EN: "Yearly" },
    discountPercent: { TR: "İndirim (%)", EN: "Discount (%)" },
    visible: { TR: "Görünür", EN: "Visible" },
    code: { TR: "Kod", EN: "Code" },
    percentOff: { TR: "İndirim (%)", EN: "Discount (%)" },
    maxUses: { TR: "En çok kullanım", EN: "Max uses" },
    expiresAt: { TR: "Bitiş", EN: "Expires" },
    days: { TR: "Gün", EN: "Days" },
    extraDaily: { TR: "Pencere başına ek mesaj", EN: "Extra messages a window" },
    role: { TR: "Rol", EN: "Role" },
    reason: { TR: "Gerekçe", EN: "Reason" },
    from: { TR: "Önceki", EN: "From" },
    to: { TR: "Yeni", EN: "To" },
    note: { TR: "Not", EN: "Note" },
    title: { TR: "Başlık", EN: "Title" },
    ownerEmail: { TR: "Sahibi", EN: "Owner" },
    authorEmail: { TR: "Yazar", EN: "Author" },
    excerpt: { TR: "Alıntı", EN: "Excerpt" },
    category: { TR: "Kategori", EN: "Category" },
    postId: { TR: "Gönderi", EN: "Post" },
    reportId: { TR: "Bildirim", EN: "Report" },
    reportsClosed: { TR: "Kapatılan bildirim", EN: "Reports closed" },
    postMissing: { TR: "Gönderi zaten yoktu", EN: "Post already gone" },
    newsId: { TR: "Haber", EN: "Story" },
    plays: { TR: "Oynanma", EN: "Plays" },
    likes: { TR: "Beğeni", EN: "Likes" },
    level: { TR: "Seviye", EN: "Level" },
    active: { TR: "Etkin", EN: "Active" },
    link: { TR: "Bağlantı", EN: "Link" },
    textTR: { TR: "Metin (TR)", EN: "Text (TR)" },
    textEN: { TR: "Metin (EN)", EN: "Text (EN)" },
    type: { TR: "Tür", EN: "Type" },
    commentId: { TR: "Yorum", EN: "Comment" },
    clearedLegacyBan: { TR: "Eski yasak kaldırıldı", EN: "Legacy ban cleared" },
    scope: { TR: "Kapsam", EN: "Scope" },
    status: { TR: "Durum", EN: "Status" },
    accountDeleted: { TR: "Hesap silindi", EN: "Account deleted" },
    accountExists: { TR: "Hesap vardı", EN: "Account existed" },
    total: { TR: "Toplam", EN: "Total" },
    errors: { TR: "Hata", EN: "Errors" },
    priority: { TR: "Öncelik", EN: "Priority" },
    ticketId: { TR: "Talep", EN: "Ticket" },
    messages: { TR: "Mesaj sayısı", EN: "Messages" },
    subscriptionId: { TR: "Paddle aboneliği", EN: "Paddle subscription" },
    customerId: { TR: "Paddle müşterisi", EN: "Paddle customer" },
    paddleDiscountId: { TR: "Paddle indirimi", EN: "Paddle discount" },
    environment: { TR: "Ortam", EN: "Environment" },
    recur: { TR: "Geçerli ödemeler", EN: "Payments" },
    createdAt: { TR: "Oluşturulma", EN: "Created" },
    createdBy: { TR: "Oluşturan", EN: "Created by" },
    paddleResult: { TR: "Paddle", EN: "Paddle" },
    plusMonth: { TR: "Plus aylık", EN: "Plus monthly" },
    plusYear: { TR: "Plus yıllık", EN: "Plus yearly" },
    proMonth: { TR: "Pro aylık", EN: "Pro monthly" },
    proYear: { TR: "Pro yıllık", EN: "Pro yearly" },
    checked: { TR: "Paddle'da doğrulandı", EN: "Checked with Paddle" },
    found: { TR: "Bulunan abonelik", EN: "Subscriptions found" },
    result: { TR: "Sonuç", EN: "Result" },
    legalName: { TR: "Yasal ad", EN: "Legal name" },
    brand: { TR: "Marka", EN: "Brand" },
    contactEmail: { TR: "İletişim e-postası", EN: "Contact e-mail" },
    address: { TR: "Adres", EN: "Address" },
    taxId: { TR: "VKN / MERSİS", EN: "Tax ID / MERSIS" },
    kep: { TR: "KEP", EN: "KEP" },
    keptBilling: { TR: "Paddle bilgisi korundu", EN: "Paddle details kept" },
    open: { TR: "Satışa açık", EN: "On sale" },
    created: { TR: "Oluşturulan", EN: "Created" },
    reused: { TR: "Var olan", EN: "Already there" },
    conflicts: { TR: "Çakışma", EN: "Conflicts" },
    currency: { TR: "Para birimi", EN: "Currency" },
};
