const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'src', 'lib', 'i18n.tsx');
let content = fs.readFileSync(file, 'utf8');

// Extract EN keys
const enMatch = content.match(/EN:\s*\{([\s\S]*?)\r?\n    \},?\r?\n    RU:/);
if (!enMatch) { console.log('Could not find EN block'); process.exit(1); }

const enBlock = enMatch[1];
const keys = [];
const enEntries = enBlock.match(/^\s+(\w+):\s*"([^"]*)"/gm);
enEntries.forEach(e => {
    const m = e.match(/^\s+(\w+):\s*"(.*)"/);
    if (m) keys.push({ key: m[1], val: m[2] });
});

console.log(`Found ${keys.length} EN keys`);

// Core translations for each language (key UI strings)
const LANGS = {
HI: { welcome:"स्वागत है",create_project:"नया प्रोजेक्ट बनाएं",select_language:"एक प्रोग्रामिंग भाषा चुनें",my_projects:"मेरे प्रोजेक्ट",save:"सहेजें",run:"चलाएं",download:"डाउनलोड",settings:"सेटिंग्स",sign_out:"लॉग आउट",login:"लॉगिन",signup:"साइन अप",no_projects:"अभी तक कोई प्रोजेक्ट नहीं",start_coding:"कोडिंग शुरू करें!",delete:"हटाएं",language:"भाषा",theme:"थीम",ai_assistant:"AI सहायक",ai_coming_soon:"जल्द आ रहा है...",save_success:"प्रोजेक्ट सफलतापूर्वक सहेजा गया!",enter_project_name:"प्रोजेक्ट का नाम दर्ज करें:",first_project:"अपना पहला प्रोजेक्ट बनाएं",recent_projects:"हालिया प्रोजेक्ट",dashboard_title:"डैशबोर्ड",dashboard_desc:"अपने प्रोजेक्ट प्रबंधित करें और नई स्क्रिप्ट बनाएं।",banner_warning:"यह एप्लिकेशन परीक्षण चरण में है, कृपया समझ दिखाएं।",why_hanogt:"Hanogt Codev बेहतर क्यों है?",hero_title_free:"जैसा चाहें स्वतंत्र रूप से कोड करें",hero_title_test:"आज़माएं और परीक्षण करें!",hero_desc:"इस 100% मुफ्त वातावरण में कोई सीमा नहीं!",cta_start:"अभी मुफ्त में उपयोग शुरू करें!",password:"पासवर्ड",confirm_password:"पासवर्ड की पुष्टि करें",profile:"प्रोफ़ाइल",back:"वापस",username:"उपयोगकर्ता नाम",email:"ईमेल",cancel:"रद्द करें",privacy_policy:"गोपनीयता नीति",all_rights_reserved:"सर्वाधिकार सुरक्षित।",loading:"लोड हो रहा है...",online:"ऑनलाइन",offline:"ऑफलाइन",friends:"मित्र",ok:"ठीक है",light:"लाइट",dark:"डार्क",terms_of_use:"उपयोग की शर्तें",about_title:"हमारे बारे में",feedback_title:"प्रतिक्रिया और FAQ",malicious_code_detected:"दुर्भावनापूर्ण कोड पाया गया!",permanently_banned:"आप स्थायी रूप से प्रतिबंधित हैं!",protected_by_hanogt_bot:"Hanogt Security Bot द्वारा सुरक्षित" },
DE: { welcome:"Willkommen",create_project:"Neues Projekt erstellen",select_language:"Programmiersprache wählen",my_projects:"Meine Projekte",save:"Speichern",run:"Ausführen",download:"Herunterladen",settings:"Einstellungen",sign_out:"Abmelden",login:"Anmelden",signup:"Registrieren",no_projects:"Noch keine Projekte",start_coding:"Starte mit dem Programmieren!",delete:"Löschen",language:"Sprache",theme:"Design",ai_assistant:"KI-Assistent",ai_coming_soon:"Kommt bald...",save_success:"Projekt erfolgreich gespeichert!",enter_project_name:"Projektname eingeben:",first_project:"Erstelle dein erstes Projekt",recent_projects:"Letzte Projekte",dashboard_title:"Dashboard",dashboard_desc:"Verwalte deine Projekte und erstelle neue Skripte.",banner_warning:"Diese Anwendung befindet sich in der Testphase.",why_hanogt:"Warum ist Hanogt Codev besser?",hero_title_free:"Programmiere frei wie du willst",hero_title_test:"Ausprobieren und Testen!",hero_desc:"In dieser 100% kostenlosen Umgebung gibt es keine Grenzen!",cta_start:"Jetzt kostenlos starten!",password:"Passwort",confirm_password:"Passwort bestätigen",profile:"Profil",back:"Zurück",username:"Benutzername",email:"E-Mail",cancel:"Abbrechen",privacy_policy:"Datenschutzrichtlinie",all_rights_reserved:"Alle Rechte vorbehalten.",loading:"Laden...",online:"Online",offline:"Offline",friends:"Freunde",ok:"OK",light:"Hell",dark:"Dunkel",terms_of_use:"Nutzungsbedingungen",about_title:"Über uns",feedback_title:"Feedback & FAQ",malicious_code_detected:"Schädlicher Code erkannt!",permanently_banned:"SIE SIND DAUERHAFT GESPERRT!",protected_by_hanogt_bot:"Geschützt durch Hanogt Security Bot" },
FR: { welcome:"Bienvenue",create_project:"Créer un nouveau projet",select_language:"Choisir un langage de programmation",my_projects:"Mes projets",save:"Enregistrer",run:"Exécuter",download:"Télécharger",settings:"Paramètres",sign_out:"Déconnexion",login:"Connexion",signup:"Inscription",no_projects:"Aucun projet pour le moment",start_coding:"Commencez à coder !",delete:"Supprimer",language:"Langue",theme:"Thème",ai_assistant:"Assistant IA",ai_coming_soon:"Bientôt disponible...",save_success:"Projet enregistré avec succès !",enter_project_name:"Entrez le nom du projet :",first_project:"Créez votre premier projet",recent_projects:"Projets récents",dashboard_title:"Tableau de bord",dashboard_desc:"Gérez vos projets et créez de nouveaux scripts.",banner_warning:"Cette application est en phase de test.",why_hanogt:"Pourquoi Hanogt Codev est-il meilleur ?",hero_title_free:"Codez librement comme vous le souhaitez",hero_title_test:"Essayez et testez !",hero_desc:"Il n'y a aucune limite dans cet environnement 100% gratuit !",cta_start:"Commencez gratuitement maintenant !",password:"Mot de passe",confirm_password:"Confirmer le mot de passe",profile:"Profil",back:"Retour",username:"Nom d'utilisateur",email:"E-mail",cancel:"Annuler",privacy_policy:"Politique de confidentialité",all_rights_reserved:"Tous droits réservés.",loading:"Chargement...",online:"En ligne",offline:"Hors ligne",friends:"Amis",ok:"OK",light:"Clair",dark:"Sombre",terms_of_use:"Conditions d'utilisation",about_title:"À propos",feedback_title:"Commentaires et FAQ",malicious_code_detected:"Code malveillant détecté !",permanently_banned:"VOUS ÊTES DÉFINITIVEMENT BANNI !",protected_by_hanogt_bot:"Protégé par Hanogt Security Bot" },
NL: { welcome:"Welkom",create_project:"Nieuw project maken",select_language:"Kies een programmeertaal",my_projects:"Mijn projecten",save:"Opslaan",run:"Uitvoeren",download:"Downloaden",settings:"Instellingen",sign_out:"Uitloggen",login:"Inloggen",signup:"Registreren",no_projects:"Nog geen projecten",start_coding:"Begin met coderen!",delete:"Verwijderen",language:"Taal",theme:"Thema",ai_assistant:"AI-assistent",ai_coming_soon:"Binnenkort...",save_success:"Project succesvol opgeslagen!",enter_project_name:"Voer projectnaam in:",first_project:"Maak je eerste project",recent_projects:"Recente projecten",dashboard_title:"Dashboard",dashboard_desc:"Beheer je projecten en maak nieuwe scripts.",banner_warning:"Deze applicatie bevindt zich in de testfase.",why_hanogt:"Waarom is Hanogt Codev beter?",hero_title_free:"Codeer vrij zoals je wilt",hero_title_test:"Probeer en test!",hero_desc:"Er zijn geen grenzen in deze 100% gratis omgeving!",cta_start:"Begin nu gratis!",password:"Wachtwoord",confirm_password:"Bevestig wachtwoord",profile:"Profiel",back:"Terug",username:"Gebruikersnaam",email:"E-mail",cancel:"Annuleren",privacy_policy:"Privacybeleid",all_rights_reserved:"Alle rechten voorbehouden.",loading:"Laden...",online:"Online",offline:"Offline",friends:"Vrienden",ok:"OK",light:"Licht",dark:"Donker",terms_of_use:"Gebruiksvoorwaarden",about_title:"Over ons",feedback_title:"Feedback & FAQ",malicious_code_detected:"Schadelijke code gedetecteerd!",permanently_banned:"U BENT PERMANENT VERBANNEN!",protected_by_hanogt_bot:"Beschermd door Hanogt Security Bot" },
PL: { welcome:"Witaj",create_project:"Utwórz nowy projekt",select_language:"Wybierz język programowania",my_projects:"Moje projekty",save:"Zapisz",run:"Uruchom",download:"Pobierz",settings:"Ustawienia",sign_out:"Wyloguj się",login:"Zaloguj się",signup:"Zarejestruj się",no_projects:"Brak projektów",start_coding:"Zacznij kodować!",delete:"Usuń",language:"Język",theme:"Motyw",ai_assistant:"Asystent AI",ai_coming_soon:"Wkrótce...",save_success:"Projekt zapisany pomyślnie!",enter_project_name:"Wpisz nazwę projektu:",first_project:"Utwórz swój pierwszy projekt",recent_projects:"Ostatnie projekty",dashboard_title:"Panel",dashboard_desc:"Zarządzaj projektami i twórz nowe skrypty.",banner_warning:"Ta aplikacja jest w fazie testowej.",why_hanogt:"Dlaczego Hanogt Codev jest lepszy?",hero_title_free:"Koduj swobodnie jak chcesz",hero_title_test:"Wypróbuj i przetestuj!",hero_desc:"W tym 100% darmowym środowisku nie ma limitów!",cta_start:"Zacznij za darmo teraz!",password:"Hasło",confirm_password:"Potwierdź hasło",profile:"Profil",back:"Wstecz",username:"Nazwa użytkownika",email:"E-mail",cancel:"Anuluj",privacy_policy:"Polityka prywatności",all_rights_reserved:"Wszelkie prawa zastrzeżone.",loading:"Ładowanie...",online:"Online",offline:"Offline",friends:"Znajomi",ok:"OK",light:"Jasny",dark:"Ciemny",terms_of_use:"Regulamin",about_title:"O nas",feedback_title:"Opinie i FAQ",malicious_code_detected:"Wykryto złośliwy kod!",permanently_banned:"ZOSTAŁEŚ TRWALE ZBANOWANY!",protected_by_hanogt_bot:"Chroniony przez Hanogt Security Bot" },
NO: { welcome:"Velkommen",create_project:"Opprett nytt prosjekt",select_language:"Velg programmeringsspråk",my_projects:"Mine prosjekter",save:"Lagre",run:"Kjør",download:"Last ned",settings:"Innstillinger",sign_out:"Logg ut",login:"Logg inn",signup:"Registrer deg",no_projects:"Ingen prosjekter ennå",start_coding:"Begynn å kode!",delete:"Slett",language:"Språk",theme:"Tema",password:"Passord",profile:"Profil",back:"Tilbake",username:"Brukernavn",email:"E-post",cancel:"Avbryt",privacy_policy:"Personvernregler",all_rights_reserved:"Alle rettigheter reservert.",loading:"Laster...",online:"Pålogget",offline:"Frakoblet",friends:"Venner",ok:"OK",light:"Lys",dark:"Mørk" },
FI: { welcome:"Tervetuloa",create_project:"Luo uusi projekti",select_language:"Valitse ohjelmointikieli",my_projects:"Projektini",save:"Tallenna",run:"Suorita",download:"Lataa",settings:"Asetukset",sign_out:"Kirjaudu ulos",login:"Kirjaudu sisään",signup:"Rekisteröidy",no_projects:"Ei projekteja vielä",start_coding:"Aloita koodaus!",delete:"Poista",language:"Kieli",theme:"Teema",password:"Salasana",profile:"Profiili",back:"Takaisin",username:"Käyttäjänimi",email:"Sähköposti",cancel:"Peruuta",privacy_policy:"Tietosuojakäytäntö",all_rights_reserved:"Kaikki oikeudet pidätetään.",loading:"Ladataan...",online:"Verkossa",offline:"Offline",friends:"Ystävät",ok:"OK",light:"Vaalea",dark:"Tumma" },
SV: { welcome:"Välkommen",create_project:"Skapa nytt projekt",select_language:"Välj programmeringsspråk",my_projects:"Mina projekt",save:"Spara",run:"Kör",download:"Ladda ner",settings:"Inställningar",sign_out:"Logga ut",login:"Logga in",signup:"Registrera dig",no_projects:"Inga projekt ännu",start_coding:"Börja koda!",delete:"Ta bort",language:"Språk",theme:"Tema",password:"Lösenord",profile:"Profil",back:"Tillbaka",username:"Användarnamn",email:"E-post",cancel:"Avbryt",privacy_policy:"Integritetspolicy",all_rights_reserved:"Alla rättigheter förbehållna.",loading:"Laddar...",online:"Online",offline:"Offline",friends:"Vänner",ok:"OK",light:"Ljus",dark:"Mörk" },
EL: { welcome:"Καλώς ήρθατε",create_project:"Δημιουργία νέου έργου",select_language:"Επιλέξτε γλώσσα προγραμματισμού",my_projects:"Τα έργα μου",save:"Αποθήκευση",run:"Εκτέλεση",download:"Λήψη",settings:"Ρυθμίσεις",sign_out:"Αποσύνδεση",login:"Σύνδεση",signup:"Εγγραφή",no_projects:"Δεν υπάρχουν έργα ακόμα",start_coding:"Ξεκινήστε να κωδικοποιείτε!",delete:"Διαγραφή",language:"Γλώσσα",theme:"Θέμα",password:"Κωδικός πρόσβασης",profile:"Προφίλ",back:"Πίσω",username:"Όνομα χρήστη",email:"Email",cancel:"Ακύρωση",privacy_policy:"Πολιτική απορρήτου",all_rights_reserved:"Με επιφύλαξη παντός δικαιώματος.",loading:"Φόρτωση...",online:"Συνδεδεμένος",offline:"Εκτός σύνδεσης",friends:"Φίλοι",ok:"OK",light:"Φωτεινό",dark:"Σκοτεινό" },
NG: { welcome:"Welcome o",create_project:"Create New Project",select_language:"Choose Programming Language",my_projects:"My Projects",save:"Save",run:"Run am",download:"Download",settings:"Settings",sign_out:"Comot",login:"Enter",signup:"Join",no_projects:"You never get project",start_coding:"Start to code!",delete:"Delete am",language:"Language",theme:"Theme",password:"Password",profile:"Profile",back:"Go back",username:"Username",email:"Email",cancel:"Cancel",privacy_policy:"Privacy Policy",all_rights_reserved:"All rights reserved.",loading:"E dey load...",online:"Online",offline:"Offline",friends:"Paddy dem",ok:"OK",light:"Light",dark:"Dark" },
BE: { welcome:"Welkom",create_project:"Nieuw project aanmaken",select_language:"Kies een programmeertaal",my_projects:"Mijn projecten",save:"Opslaan",run:"Uitvoeren",download:"Downloaden",settings:"Instellingen",sign_out:"Afmelden",login:"Aanmelden",signup:"Registreren",no_projects:"Nog geen projecten",start_coding:"Begin met coderen!",delete:"Verwijderen",language:"Taal",theme:"Thema",password:"Wachtwoord",profile:"Profiel",back:"Terug",username:"Gebruikersnaam",email:"E-mail",cancel:"Annuleren",privacy_policy:"Privacybeleid",all_rights_reserved:"Alle rechten voorbehouden.",loading:"Aan het laden...",online:"Online",offline:"Offline",friends:"Vrienden",ok:"OK",light:"Licht",dark:"Donker" },
};

// For each new language, build a full translation block using EN as fallback
const insertions = [];
for (const [langCode, coreTranslations] of Object.entries(LANGS)) {
    let block = `    ${langCode}: {\n`;
    for (const { key, val } of keys) {
        const translated = coreTranslations[key] || val;
        // Escape quotes in value
        const escaped = translated.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        block += `        ${key}: "${escaped}",\n`;
    }
    block += `    },`;
    insertions.push(block);
}

const insertText = '\n' + insertions.join('\n') + '\n';

// Insert before the closing `};` of DICTIONARY
const insertPoint = content.lastIndexOf('\n};');
if (insertPoint === -1) { console.log('Could not find end of DICTIONARY'); process.exit(1); }

content = content.slice(0, insertPoint) + insertText + content.slice(insertPoint);

fs.writeFileSync(file, content, 'utf8');
console.log(`Successfully added ${Object.keys(LANGS).length} new languages with ${keys.length} keys each.`);
