import type { EditableAccountFields } from "@/lib/account-profile";
import type { Copy } from "@/lib/i18n";

/** Account Settings copy. Existing English strings are kept as they were, so their translations stay. */
export const C = {
    title: { TR: "Hesap Ayarları", EN: "Account Settings" },
    subtitle: { TR: "Profilinizi, gizlilik ve güvenlik ayarlarınızı, bildirimlerinizi ve uygulama tercihlerinizi tek yerden yönetin.", EN: "Manage your profile, privacy and security, notifications and app preferences in one place." },
    settings: { TR: "Ayarlar", EN: "Settings" },
    groupUser: { TR: "Kullanıcı ayarları", EN: "User settings" },
    groupApp: { TR: "Uygulama ayarları", EN: "App settings" },
    groupData: { TR: "Hesap", EN: "Account" },
    backToList: { TR: "Ayarlara dön", EN: "Back to settings" },
    search: { TR: "Ayarlarda ara…", EN: "Search settings…" },
    results: { TR: "Eşleşen ayarlar", EN: "Matching settings" },
    resultCount: { TR: "{count} ayar bulundu", EN: "{count} settings found" },
    noMatch: { TR: "“{query}” ile eşleşen bir ayar yok.", EN: "No setting matches “{query}”." },
    clearSearch: { TR: "Aramayı temizle", EN: "Clear search" },
    instant: { TR: "Anında kaydedilir", EN: "Saved instantly" },
    deviceInstant: { TR: "Bu cihazda anında uygulanır", EN: "Applies instantly on this device" },

    loading: { TR: "Hesap bilgileriniz yükleniyor…", EN: "Loading your account…" },
    loadErrorTitle: { TR: "Profiliniz yüklenemedi", EN: "Your profile couldn't be loaded" },
    retry: { TR: "Tekrar dene", EN: "Try again" },
    signInAgain: { TR: "Yeniden giriş yap", EN: "Sign in again" },
    otherSettingsStillWork: { TR: "Dil, tema, güvenlik ve hesap işlemleri kullanılmaya devam eder.", EN: "Language, theme, security and account actions keep working." },

    saveBar: { TR: "Kayıt durumu", EN: "Save status" },
    unsaved: { TR: "Kaydedilmemiş değişiklikler", EN: "You have unsaved changes" },
    unsavedCount: { TR: "{count} alan değişti", EN: "{count} fields changed" },
    save: { TR: "Değişiklikleri kaydet", EN: "Save changes" },
    saveHint: { TR: "Kaydet (Ctrl/⌘+S)", EN: "Save (Ctrl/⌘+S)" },
    saving: { TR: "Kaydediliyor…", EN: "Saving…" },
    discard: { TR: "Sıfırla", EN: "Reset" },
    discardHint: { TR: "Kaydedilmemiş değişiklikleri geri al", EN: "Undo the unsaved changes" },
    saved: { TR: "Değişiklikleriniz kaydedildi.", EN: "Your changes were saved." },
    discarded: { TR: "Değişiklikler geri alındı.", EN: "The changes were discarded." },
    nothingToSave: { TR: "Kaydedilecek değişiklik yok.", EN: "There's nothing to save." },
    fieldProblem: { TR: "{field}: {problem}", EN: "{field}: {problem}" },
    settingSaved: { TR: "Ayar kaydedildi.", EN: "Setting saved." },
    settingFailed: { TR: "Ayar kaydedilemedi. Tekrar deneyin.", EN: "Couldn't save the setting. Try again." },

    // Hesabım
    overview: { TR: "Hesap özeti", EN: "Account overview" },
    editProfile: { TR: "Profili düzenle", EN: "Edit profile" },
    memberSince: { TR: "Üyelik", EN: "Member since" },
    lastSignIn: { TR: "Son giriş", EN: "Last sign-in" },
    security: { TR: "Güvenlik", EN: "Security" },
    twoFactorOn: { TR: "İki adımlı doğrulama açık", EN: "Two-step verification is on" },
    twoFactorOff: { TR: "İki adımlı doğrulama kapalı", EN: "Two-step verification is off" },
    passwordOn: { TR: "Şifre ayarlı", EN: "Password set" },
    passwordOff: { TR: "Yalnızca Google ile giriş", EN: "Google sign-in only" },
    securityLoading: { TR: "Güvenlik durumu yükleniyor", EN: "Loading the security status" },
    manageSecurity: { TR: "Güvenliği yönet", EN: "Manage security" },
    statsLabel: { TR: "Hesap istatistikleri", EN: "Account statistics" },
    statProjects: { TR: "Proje", EN: "Projects" },
    statGameProjects: { TR: "Oyun projesi", EN: "Game projects" },
    statGroups: { TR: "Grup", EN: "Groups" },
    statFriends: { TR: "Arkadaş", EN: "Friends" },
    statPosts: { TR: "Paylaşım", EN: "Posts" },
    identity: { TR: "Kimlik", EN: "Identity" },
    identityHint: { TR: "Arkadaşlarınız sizi takma ad ve etiketle bulur.", EN: "Friends find you by nickname and tag." },
    usernameHint: { TR: "Profilinizde ve mesajlarda görünen adınız.", EN: "The name shown on your profile and in messages." },
    emailHint: { TR: "Giriş adresiniz; buradan değiştirilemez.", EN: "Your sign-in address; it can't be changed here." },
    copyTag: { TR: "Takma adı ve etiketi kopyala", EN: "Copy nickname and tag" },
    tagCopied: { TR: "{tag} panoya kopyalandı.", EN: "{tag} was copied to the clipboard." },
    copyFailed: { TR: "Panoya kopyalanamadı.", EN: "Couldn't copy to the clipboard." },
    newTag: { TR: "Yeni etiket", EN: "New tag" },
    newTagHint: { TR: "Rastgele yeni bir 4 haneli etiket seçer; kaydettiğinizde arkadaşlarınız sizi yeni etiketle bulur.", EN: "Picks a new random 4-digit tag; once you save, friends find you with the new tag." },
    tagLabel: { TR: "Etiket", EN: "Tag" },
    session: { TR: "Oturum", EN: "Session" },
    providerPassword: { TR: "E-posta ve şifre", EN: "E-mail and password" },
    signOutHere: { TR: "Bu cihazda çıkış yap", EN: "Sign out on this device" },

    // Profil
    picture: { TR: "Profil resmi ve kapak", EN: "Picture and banner" },
    avatarHint: { TR: "Profil kartınızda ve mesajlarınızın yanında görünür.", EN: "Shown on your profile card and next to your messages." },
    bannerHint: { TR: "Profil kartınızın üst kısmında görünür.", EN: "Shown across the top of your profile card." },
    accentHint: { TR: "Kapak görseli yoksa kartınızın üst şeridi ve favori dil etiketleriniz bu renkte görünür.", EN: "Without a banner, your card's top strip and your language tags use this colour." },
    urlInvalid: { TR: "https:// ile başlayan, boşluk içermeyen bir resim adresi girin.", EN: "Enter an image address that starts with https:// and has no spaces." },
    accentOption: { TR: "Vurgu rengi {color}", EN: "Accent colour {color}" },
    about: { TR: "Hakkınızda", EN: "About you" },
    bioHint: { TR: "Profil kartınızda görünür.", EN: "Shown on your profile card." },
    preview: { TR: "Önizleme", EN: "Preview" },
    previewHint: { TR: "Başkalarının profil kartınızda göreceği hâli; kaydetmeden önce de güncellenir.", EN: "What others see on your profile card; it updates before you save." },
    planBadgeTitle: { TR: "Plan rozeti", EN: "Plan badge" },
    planBadgeTeaser: { TR: "Plus ya da Pro aboneliğinizle adınızın yanında bir rozet görünür.", EN: "With a Plus or Pro subscription, a badge appears next to your name." },
    seePlans: { TR: "Planları gör", EN: "See the plans" },

    // Durum
    statusTitle: { TR: "Durumunuz", EN: "Your status" },
    statusHint: { TR: "Profil resminizin sağ altındaki işaret: seçtiğiniz anda kaydedilir.", EN: "The mark at the bottom right of your picture; saved as soon as you pick it." },
    statusNow: { TR: "Şu an görünen: {status}", EN: "Shown right now: {status}" },
    visibility: { TR: "Görünürlük", EN: "Visibility" },
    visibilityDescription: { TR: "Başkalarının sizi ne zaman çevrimiçi göreceğini belirleyin.", EN: "Choose when others see you online." },
    onlineHidden: { TR: "Kapalıyken herkes sizi çevrimdışı görür (Görünmez gibi).", EN: "While off, everyone sees you as offline (like Invisible)." },
    lastSeenHint: { TR: "Kapalıyken çevrimdışıyken ne zaman görüldüğünüz gösterilmez.", EN: "While off, nobody sees when you were last online." },

    // Gizlilik ve Güvenlik
    passwordTitle: { TR: "Şifre", EN: "Password" },
    passwordStepUpNote: { TR: "Şifre belirlediğinizde Google ile her girişte bu şifre, iki adımlı doğrulama açıksa kod da sorulur.", EN: "Once you set a password, every Google sign-in asks for it too, plus the code when two-step verification is on." },
    currentPassword: { TR: "Mevcut şifre", EN: "Current password" },
    newPassword: { TR: "Yeni şifre", EN: "New password" },
    confirmPassword: { TR: "Yeni şifre (tekrar)", EN: "New password (again)" },
    newPasswordHint: { TR: "En az 10 karakter.", EN: "At least 10 characters." },
    passwordWrong: { TR: "Mevcut şifre yanlış.", EN: "The current password is wrong." },
    passwordSavedOthersOut: { TR: "Şifreniz kaydedildi; diğer cihazlardaki oturumlarınız kapatıldı.", EN: "Your password was saved and your other devices were signed out." },
    reauthPassword: { TR: "Güvenliğiniz için şifre belirlemeden önce yeniden giriş yapmanız gerekiyor (son 30 dakika içinde).", EN: "For your security, sign in again before setting a password (within the last 30 minutes)." },
    reauthDelete: { TR: "Hesabınızı silmek için son 30 dakika içinde giriş yapmış olmanız gerekiyor. Yeniden giriş yapıp tekrar deneyin.", EN: "To delete your account, you need to have signed in within the last 30 minutes. Sign in again and try once more." },
    twoFactor: { TR: "İki adımlı doğrulama", EN: "Two-step verification" },
    sessionsTitle: { TR: "Oturumlar", EN: "Sessions" },
    sessionsHint: { TR: "Hesabınız başka bir cihazda ya da tarayıcıda açık kaldıysa hepsini buradan kapatın; bu cihazdaki oturumunuz açık kalır. Şifrenizi değiştirdiğinizde de diğer oturumlar kapanır.", EN: "If your account is still signed in on another device or browser, sign them all out here; you stay signed in on this device. Changing your password signs the other sessions out too." },
    signOutOthers: { TR: "Diğer tüm oturumları kapat", EN: "Sign out all other sessions" },
    signOutOthersDone: { TR: "Diğer tüm oturumlarınız kapatıldı; bu cihazda oturumunuz açık.", EN: "All your other sessions were signed out; you're still signed in here." },
    signOutOthersFailed: { TR: "Oturumlar şu anda kapatılamadı. Biraz sonra tekrar deneyin.", EN: "Couldn't sign the sessions out right now. Try again in a moment." },
    tooManyTries: { TR: "Çok sık denediniz. Biraz bekleyip tekrar deneyin.", EN: "You tried too often. Wait a little and try again." },
    profileVisibility: { TR: "Profil ve içerik görünürlüğü", EN: "Profile and content visibility" },
    publicProfileHint: { TR: "Kapalıyken profil kartınızı yalnızca arkadaşlarınız, mesajlaştığınız kişiler ve ortak gruplarınızın üyeleri görebilir.", EN: "When off, only your friends, people you've messaged and members of your groups can see your profile card." },
    bioVisibilityHint: { TR: "Hanogt Social'daki profil kartınızda geçerlidir.", EN: "Applies to your profile card in Hanogt Social." },
    friendRequests: { TR: "Arkadaşlık istekleri", EN: "Friend requests" },

    // Bildirimler
    inApp: { TR: "Site içi bildirimler", EN: "In-app notifications" },
    inAppHint: { TR: "Zil simgesinde görünen bildirimler.", EN: "Notifications shown under the bell." },
    messageNotificationsHint: { TR: "Biri size mesaj gönderdiğinde.", EN: "When someone sends you a message." },
    mentionNotifications: { TR: "Gruplarda bahsedilme bildirimleri", EN: "Group mention notifications" },
    mentionNotificationsHint: { TR: "Hanogt Social gruplarında biri sizden @ ile bahsettiğinde.", EN: "When someone @mentions you in a Hanogt Social group." },
    callNotificationsHint: { TR: "Yanıtlayamadığınız sesli aramalar.", EN: "Voice calls you couldn't answer." },
    friendRequestNotificationsHint: { TR: "Biri size arkadaşlık isteği gönderdiğinde.", EN: "When someone sends you a friend request." },
    groupLevels: { TR: "Her grubun bildirim düzeyini (tüm mesajlar, yalnızca bahsetmeler, hiçbiri) grubun menüsünden ayrıca seçebilirsiniz.", EN: "You can also pick each group's notification level (all messages, mentions only, nothing) from the group's menu." },

    // Mesajlaşma
    chat: { TR: "Sohbet", EN: "Chat" },
    chatLook: { TR: "Sohbet görünümü", EN: "Chat look" },
    typingHint: { TR: "Kapalıyken yazdığınız görünmez ve başkalarının yazdığını da görmezsiniz.", EN: "When off, nobody sees you typing and you don't see others typing." },
    receiptsHint: { TR: "Kapalıyken direkt mesajlarda karşı taraf mesajını gördüğünüzü bilmez; siz de onunkini göremezsiniz.", EN: "When off, the other person in a direct message doesn't see that you read their message, and you don't see it either." },
    gifHint: { TR: "Kapalıyken GIF'ler üzerine gelince ya da dokununca oynar. Sistemin hareketi azalt ayarı da GIF'leri durdurur.", EN: "When off, GIFs play when you hover or tap them. Your system's reduce motion setting stops them too." },
    enterHint: { TR: "Kapalıyken Enter yeni satır ekler; göndermek için Ctrl+Enter (Mac'te ⌘+Enter) kullanılır.", EN: "When off, Enter adds a new line and Ctrl+Enter (⌘+Enter on Mac) sends." },

    // Görünüm
    theme: { TR: "Tema", EN: "Theme" },
    themeLight: { TR: "Açık", EN: "Light" },
    themeDark: { TR: "Koyu", EN: "Dark" },
    themeSystem: { TR: "Sistem", EN: "System" },
    language: { TR: "Dil", EN: "Language" },
    accessibility: { TR: "Erişilebilirlik", EN: "Accessibility" },
    accessibilityHint: { TR: "Hesabınıza bağlıdır; giriş yaptığınız her cihazda geçerli olur.", EN: "Kept with your account; it applies on every device you sign in on." },
    reduceAnimationsHint: { TR: "Geçişler, kayan yazılar ve renk akışları durur. Cihazınızın “hareketi azalt” ayarı da her zaman dikkate alınır.", EN: "Transitions, moving text and flowing colours stop. Your device's “reduce motion” setting is always respected too." },
    highContrastHint: { TR: "İkincil yazılar ve çizgiler daha belirgin olur.", EN: "Secondary text and lines get stronger." },

    // Editör, Hanogt AI
    editorTitle: { TR: "Kod editörü", EN: "Code editor" },
    editorHint: { TR: "Yazı tipi, tema, kısayollar ve çalıştırma ayarları editörün kendi sayfasında.", EN: "Font, theme, shortcuts and run settings are on the editor's own page." },
    openEditorSettings: { TR: "Editör ayarlarını aç", EN: "Open editor settings" },
    editorResetFailed: { TR: "Editör ayarları bu cihazda sıfırlandı ancak hesabınıza kaydedilemedi.", EN: "The editor settings were reset on this device but couldn't be saved to your account." },
    resetEditorTitle: { TR: "Editör ayarları sıfırlansın mı?", EN: "Reset the editor settings?" },
    resetEditorText: { TR: "Yazı tipi, tema, kısayollar ve diğer editör tercihleriniz varsayılana döner. Hesabınızla eşitlenen kopya da sıfırlanır; bu işlem geri alınamaz.", EN: "Your font, theme, shortcuts and other editor preferences go back to their defaults. The copy synced with your account is reset too; this can't be undone." },
    aiTitle: { TR: "Hanogt AI ayarları", EN: "Hanogt AI settings" },
    aiHint: { TR: "Hanogt AI'ın sizi nasıl yanıtlayacağını (talimatlar, üslup, uzunluk, dil), yeni sohbetlerin varsayılanlarını ve sohbet geçmişinizi yönetin.", EN: "Choose how Hanogt AI answers you (instructions, tone, length, language), how new chats start, and manage your chat history." },
    openHanogtAiSettings: { TR: "Hanogt AI ayarlarını aç", EN: "Open Hanogt AI settings" },
    aiUsage: { TR: "Kullanımım", EN: "My usage" },

    // Veri
    exportTitle: { TR: "Verilerinizi indirin", EN: "Download your data" },
    dangerTitle: { TR: "Tehlikeli bölge", EN: "Danger zone" },
} satisfies Record<string, Copy>;

/** Messages for the `code` of /api/account/profile errors (and network failures). */
export const SAVE_ERRORS: Record<string, Copy> = {
    unauthorized: { TR: "Oturumunuz sona ermiş. Değişikliklerinizi kaybetmemek için yeni bir sekmede giriş yapıp tekrar kaydedin.", EN: "Your session has ended. Sign in in a new tab, then save again so your changes aren't lost." },
    bad_origin: { TR: "İstek güvenlik denetiminden geçemedi. Sayfayı yenileyip tekrar deneyin.", EN: "The request failed a security check. Reload the page and try again." },
    rate_limited: { TR: "Çok sık kaydettiniz. Biraz bekleyip tekrar deneyin.", EN: "You saved too often. Wait a moment and try again." },
    invalid_body: { TR: "Değişiklikler gönderilemedi. Sayfayı yenileyip tekrar deneyin.", EN: "The changes couldn't be sent. Reload the page and try again." },
    unknown_field: { TR: "Değişiklikler gönderilemedi. Sayfayı yenileyip tekrar deneyin.", EN: "The changes couldn't be sent. Reload the page and try again." },
    nickname_taken: { TR: "Bu takma ad ve etiket başka bir hesapta kullanılıyor. Takma adınızı değiştirin veya “Yeni etiket” ile başka bir etiket alın.", EN: "This nickname and tag are used by another account. Change your nickname or get another tag with “New tag”." },
    unavailable: { TR: "Profil hizmeti şu anda kullanılamıyor. Değişiklikleriniz bu sayfada duruyor; biraz sonra tekrar kaydedin.", EN: "The profile service is unavailable right now. Your changes are still on this page; save again in a moment." },
    network: { TR: "Sunucuya bağlanılamadı. İnternet bağlantınızı kontrol edip tekrar kaydedin.", EN: "Couldn't reach the server. Check your internet connection and save again." },
    unknown: { TR: "Kaydedilemedi. Lütfen tekrar deneyin.", EN: "Couldn't save. Please try again." },
};

export const LOAD_ERRORS: Record<string, Copy> = {
    unauthorized: { TR: "Oturumunuz doğrulanamadı. Lütfen yeniden giriş yapın.", EN: "Your session couldn't be verified. Please sign in again." },
    rate_limited: { TR: "Kısa sürede çok fazla istek yapıldı. Biraz bekleyip tekrar deneyin.", EN: "Too many requests in a short time. Wait a moment and try again." },
    network: { TR: "Sunucuya bağlanılamadı. İnternet bağlantınızı kontrol edin.", EN: "Couldn't reach the server. Check your internet connection." },
    unknown: { TR: "Profil bilgileriniz şu anda alınamadı. Bu genellikle geçici bir sunucu sorunudur; verileriniz güvende.", EN: "Your profile details couldn't be fetched right now. This is usually a temporary server problem; your data is safe." },
};

export const PROBLEMS: Record<string, Copy> = {
    type: { TR: "değer biçimi hatalı", EN: "the value has the wrong format" },
    too_long: { TR: "çok uzun", EN: "too long" },
    invalid: { TR: "geçersiz", EN: "invalid" },
    required: { TR: "boş bırakılamaz", EN: "can't be empty" },
};

/** Names of the text fields a save error can point at. */
export const FIELD_LABELS: Partial<Record<keyof EditableAccountFields, Copy>> = {
    username: { TR: "Kullanıcı adı", EN: "Username" },
    nickname: { TR: "Takma ad", EN: "Nickname" },
    nicknameTag: { TR: "Etiket", EN: "Tag" },
    avatarUrl: { TR: "Profil resmi adresi", EN: "Profile picture URL" },
    bannerUrl: { TR: "Kapak görseli adresi", EN: "Banner URL" },
    bio: { TR: "Hakkında", EN: "About" },
    customStatus: { TR: "Özel durum", EN: "Custom status" },
    accentColor: { TR: "Vurgu rengi", EN: "Accent colour" },
    favoriteLangs: { TR: "Favori diller", EN: "Favourite languages" },
    socialGithub: { TR: "GitHub", EN: "GitHub" },
    socialLinkedin: { TR: "LinkedIn", EN: "LinkedIn" },
    socialTwitter: { TR: "Twitter / X", EN: "Twitter / X" },
    socialWebsite: { TR: "Web sitesi", EN: "Website" },
    socialYoutube: { TR: "YouTube", EN: "YouTube" },
    socialTiktok: { TR: "TikTok", EN: "TikTok" },
    socialInstagram: { TR: "Instagram", EN: "Instagram" },
    socialFacebook: { TR: "Facebook", EN: "Facebook" },
};
