import LegalPage, { LegalSection } from "@/components/LegalPage";

const sections: LegalSection[] = [
    { id: "contract", title: "Sözleşmenin kapsamı ve kabul", paragraphs: ["Bu şartlar Hanogt Codev web, masaüstü ve mobil uygulamalarının kullanımını düzenler. Hesap açarak veya hizmeti kullanarak şartların o tarihteki sürümünü kabul edersiniz. Reşit olmayan kullanıcılar için uygulanabilir hukuk uyarınca veli/vasi onayı gerekebilir.", "İşletmecinin kesin ticari unvanı, adresi, MERSİS/VKN ve iletişim kanalı üretim öncesinde yayımlanmalıdır. Ücretli hizmet başlatılırsa mesafeli sözleşme ön bilgilendirmesi, fiyat, cayma hakkı ve dijital içerik istisnaları ayrıca sunulur."] },
    { id: "service", title: "Hizmetin niteliği", paragraphs: ["Hanogt Codev kod düzenleme, web tabanlı 2D/3D sahne oluşturma, oyun projesi ve C#/C++ script saklama, mesajlaşma, sesli mesaj, eşler arası sesli arama ve isteğe bağlı yapay zekâ/kod çalıştırma özellikleri sunar. Kod çalıştırma özelliği yalnızca yönetilen ve izole yürütücü yapılandırıldığında kullanılabilir. Kesintisiz veya hatasız hizmet garantisi verilmez; planlı bakım ve güvenlik müdahaleleri yapılabilir.", "Oyun motoru bir masaüstü Unity dağıtımı veya yerel C#/C++ derleyicisi değildir. Sahne önizlemesi tarayıcı çalışma zamanında yürütülür; C#/C++ kaynakları editörde hazırlanır ve yalnız yapılandırılmış izole runner ile ayrı test işi olarak çalıştırılabilir. Runner sonucu, scriptin sahneye güvenli biçimde bağlandığı veya dağıtıma hazır oyun üretildiği anlamına gelmez."] },
    { id: "game-engine", title: "Oyun motoru projeleri", paragraphs: ["Oyun projesi; sahne hiyerarşisi, nesne kimliği, dönüşüm ve bileşen ayarlarıyla C#/C++ script kaynaklarını saklar. Kullanıcı uyumlu tarayıcı, ekran kartı ve WebGL desteğinin sonuçları etkileyebileceğini kabul eder. Kritik değişikliklerden önce dışa aktarma ve sürüm kontrolü önerilir.", "C# ve C++ script şablonları kullanıcıya aittir. Kodun derlenmesi, üçüncü taraf bağımlılıklar, lisanslar, performans, ağ erişimi ve hedef platform paketlemesi ayrıca doğrulanmalıdır. Önizleme fiziği ve bileşen davranışları prototipleme amaçlı ilk sürüm sınırlarına sahiptir; kesin fizik veya ticari motor uyumluluğu garantisi verilmez."] },
    { id: "account", title: "Hesap güvenliği", items: ["Doğru ve güncel bilgi sağlamak, güçlü ve benzersiz parola kullanmak kullanıcının sorumluluğundadır.", "Hesap devredilemez; şüpheli erişim derhâl bildirilmelidir.", "Otomasyonla hesap açma, kimlik taklidi, oturum veya hız sınırı aşma girişimi yasaktır.", "İhlal şüphesinde önce orantılı kısıtlama ve inceleme uygulanır; otomatik tespit tek başına geri dönülmez kalıcı yaptırım sayılmaz."] },
    { id: "content", title: "Kullanıcı içeriği ve fikrî haklar", paragraphs: ["Kullanıcı, yüklediği kod ve içeriğin hak sahibi olduğunu veya gerekli izne sahip bulunduğunu taahhüt eder. İçeriğin mülkiyeti kullanıcıda kalır. Hizmetin çalışması, yedeklenmesi, görüntülenmesi ve kullanıcı talebiyle çalıştırılması için sınırlı, geri alınabilir ve hizmet süresiyle bağlı teknik lisans verilir.", "5846 sayılı Fikir ve Sanat Eserleri Kanunu kapsamındaki mali ve manevi haklar ile üçüncü kişilerin marka, patent, ticari sır ve kişilik hakları ihlal edilemez. Bu kullanım şartı, kullanıcı içeriğinin hak sahipliğini Hanogt'a devretmez. Usulüne uygun ihlal bildirimi incelenir; gerektiğinde içerik erişimi geçici olarak sınırlandırılır."] },
    { id: "media-license", title: "Hanogt Media yayın ve indirme kuralları", paragraphs: ["Media’ya yayınlama, kaynak dosyalarını internetten görüntülenebilir ve indirilebilir hâle getirir. Bu, tek başına açık kaynak lisansı seçildiği anlamına gelmez. Yayıncı, yeniden kullanım koşullarını proje açıklamasında veya lisans dosyasında belirtmelidir. Lisans belirtilmemiş içerik yalnızca platform işlevi kapsamında görüntülenip kişisel inceleme için indirilebilir; telif mevzuatının tanımadığı ek kullanım hakkı doğmaz.", "Yayıncı; kodda kişisel veri, sır, erişim anahtarı veya üçüncü kişiye ait izinsiz içerik bulunmadığını kontrol eder. İndiren kullanıcı ise bağımlılıkları, güvenliği ve lisansı kendi ortamında doğrulamadan kodu çalıştırmamalıdır. Beğeni sıralaması kalite veya güvenlik garantisi değildir."], items: ["Zararlı kod, yanıltıcı başlık, spam ve yapay etkileşim yasaktır.", "Telif veya kişilik hakkı ihlali bildirimi gerekçesi ve hak sahipliği bilgisiyle gönderilmelidir.", "Acil riskte yayın geçici gizlenebilir; yayıncıya itiraz ve açıklama olanağı sağlanır.", "Yayın silinse dahi daha önce üçüncü kişilerce hukuka uygun indirilen kopyaların uzaktan silinmesi teknik olarak mümkün değildir."] },
    { id: "groups", title: "Grup ve ortak çalışma kuralları", paragraphs: ["Grup üyesi yalnızca kendi arkadaşı olan kullanıcıyı davet edebilir; davet edilen kişi üyelikten ayrılabilir ve uygunsuz davranışı bildirebilir. Üyeler grup içinde gördükleri e-posta, profil, kod, mesaj ve sesli mesajları grup amacı dışında kullanamaz veya izinsiz yayımlayamaz.", "Ortak editör anlık senkronizasyon sunar ancak tam bir sürüm kontrol sistemi veya çakışmasız CRDT garantisi vermez. Eş zamanlı yazmalarda son kayıt baskın olabilir. Ticari veya kritik kaynaklar için Git gibi sürüm kontrolü, yedek ve erişim politikası kullanılmalıdır."], items: ["Grup sahibi yönetimden ve üye erişimlerinin güncelliğinden sorumludur.", "Bir üyeyi eklemek, o üyeye ortak proje ve geçmiş grup sohbeti erişimi verebilir.", "Sesli mesaj bilerek kaydedilen kalıcı içeriktir; WebRTC arama sesi ise Hanogt tarafından kaydedilmez.", "Bir üyeye ait hesabın silinmesi üyeliği kaldırır; diğer üyelerin meşru mesaj bütünlüğü ile silme hakları dengelenir."] },
    { id: "security-program", title: "Security Bot gönüllü katkı programı", paragraphs: ["Program varsayılan kapalıdır ve temel hizmetin şartı değildir. Kullanıcı yalnızca ayrıca seçtiği yayımlanmış projeyi insan denetimli güvenlik geliştirme değerlendirmesine aday gösterir. Hanogt; amacı, erişebilen rolleri, saklama süresini ve varsa model eğitimi yöntemini belgelemeden ham kodu kontrolsüz otomatik eğitimde kullanmaz.", "Kullanıcı hesap düzeyindeki izni geri çekebilir. Geri çekme yeni işlemeyi durdurur ve bekleyen katkı kayıtlarını silme sürecine alır; kanunen saklanması gereken kayıtlar ve geri döndürülmesi teknik olarak mümkün olmayan, usulüne uygun anonimleştirilmiş istatistikler bakımından yasal istisnalar saklıdır."] },
    { id: "acceptable-use", title: "Kabul edilebilir kullanım", items: ["Zararlı yazılım yayma, kimlik bilgisi toplama, ters kabuk, kaynak tüketimi veya üçüncü sistemlere saldırı amacıyla hizmet kullanılamaz.", "Taciz, nefret, tehdit, dolandırıcılık, müstehcen veya hukuka aykırı içerik gönderilemez.", "Başkalarının gizliliği ihlal edilemez; sesli arama kaydı yapılacaksa tarafların bilgisi ve uygulanabilir rızası ayrıca alınmalıdır. Hanogt Codev aramayı kaydetmez.", "Güvenlik araştırması yalnızca açıkça izinli kapsamda yapılmalıdır. Yanlış pozitif tespitler için geri bildirim/itiraz yolu kullanılabilir."] },
    { id: "moderation", title: "İhlal, inceleme ve itiraz", paragraphs: ["Riskli istek anlık olarak engellenebilir ve asgari bir denetim kaydı oluşturulabilir. Hesap kısıtlaması; ihlalin niteliği, tekrar durumu, zararın ağırlığı ve kullanıcının açıklaması değerlendirilerek uygulanır. Acil risk dışında kullanıcıya sebep ve itiraz kanalı bildirilir.", "Kullanıcı, Geri Bildirim ve SSS sayfasındaki Güvenlik İtirazı kategorisinden inceleme talep edebilir. Açık hata hâlinde kayıt düzeltilir ve kısıtlama kaldırılır."] },
    { id: "platform-law", title: "İçerik bildirimi ve platform yükümlülükleri", paragraphs: ["Hanogt Codev'in somut faaliyette 5651 sayılı Kanun bakımından hangi hizmet sağlayıcı sıfatına girdiği, yerleşiklik ve faaliyet modeli kesinleştiğinde ayrıca değerlendirilir. Uygulanabilir olduğu ölçüde yetkili makam kararları ve hukuka uygun erişim/içerik çıkarma bildirimleri kayıt altına alınır, kapsamıyla sınırlı uygulanır ve kanunen yasak değilse içerik sahibine bilgi verilir.", "Telif veya kişilik hakkı bildiriminde bildirilen bağlantı/içerik, hak sahipliği dayanağı, iletişim bilgisi ve gerekçe istenir. Açıkça kötüye kullanılan bildirimler kabul edilmez; karşı açıklama ve insan incelemesi yolu korunur. Platform, sırf rapor sayısına dayanarak otomatik ve geri dönülmez karar vermez."] },
    { id: "third-parties", title: "Üçüncü taraf hizmetleri", paragraphs: ["Google/Firebase, Google OAuth, AI sağlayıcısı, TURN/STUN ve yapılandırılan kod yürütücüsü kendi koşul ve kullanılabilirliklerine tabidir. Hanogt Codev bu hizmetlere ilişkin bağımlılıkları açıklar; üçüncü taraf altyapısını kendisine aitmiş gibi sunmaz. Kullanıcı tarafından AI veya çalıştırıcıya gönderilen kodda gizli anahtar bulunmamalıdır."] },
    { id: "liability", title: "Sorumluluk ve tüketici hakları", paragraphs: ["Hizmet “olduğu gibi” sunulsa da 6098 sayılı Türk Borçlar Kanunu ve diğer emredici hükümler uyarınca tüketici hukuku, ayıplı hizmet, kişisel veri ve kast/ağır kusurdan doğan sorumluluk bertaraf edilmez. Kullanıcı, kod çıktısını üretim ortamında kullanmadan önce test etmek ve yedek almakla yükümlüdür.", "Ücretli sürüm sunulursa 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği kapsamındaki satıcı/sağlayıcı bilgisi, toplam fiyat, ön bilgilendirme, ödeme, ifa, fesih, cayma hakkı ve dijital içerik istisnaları siparişten önce ayrıca gösterilir.", "Ticari elektronik ileti gönderilirse 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun kapsamındaki onay, ret ve gerekli kayıt süreçleri işletilir. Hesap güvenliği ve hizmetin ifasına ilişkin zorunlu bildirimler pazarlama onayı olarak kullanılmaz."] },
    { id: "termination", title: "Fesih, veri alma ve silme", paragraphs: ["Kullanıcı hesabını ayarlardan kapatabilir ve önce veri kopyasını indirebilir. Silme; yasal saklama zorunluluğu ve diğer kullanıcıların meşru iletişim kayıtları dikkate alınarak uygulanır. Hizmet, esaslı şart değişikliğinde kullanıcıya makul bildirim sağlar."] },
    { id: "changes", title: "Değişiklikler, sürümleme ve bölünebilirlik", paragraphs: ["Şartlarda kullanıcı aleyhine esaslı değişiklik yapılırsa yürürlükten önce anlaşılır bildirim sunulur; gerekiyorsa yeniden kabul veya ayrı rıza alınır. Değişiklik günlüğü sürüm ve yürürlük tarihiyle korunur. Kullanıcının değişikliği kabul etmemesi hâlinde verisini dışa aktarıp hesabını kapatma hakkı saklıdır.", "Bir hükmün geçersiz olması diğer hükümlerin geçerliliğini kendiliğinden etkilemez. Emredici hukukla çelişen hükümler, emredici düzenlemeye uygun en dar kapsamda uygulanır. Türkçe metin ile çeviriler arasında çelişki olursa tüketici aleyhine yorum yasağı ve emredici hükümler saklı kalmak üzere Türkçe metin esas alınır."] },
    { id: "law", title: "Uygulanacak hukuk ve uyuşmazlık", paragraphs: ["Türkiye Cumhuriyeti hukuku uygulanır. Tüketici sıfatı bulunan kullanıcıların tüketici hakem heyeti, tüketici mahkemesi ve yerleşim yeri yetkileri saklıdır. Diğer uyuşmazlıklarda emredici yetki kuralları saklı kalmak üzere işletmecinin merkezinin bulunduğu yer mahkemeleri yetkilidir."] },
];

export default function TermsOfUsePage() {
    return <LegalPage eyebrow="Hizmet koşulları" title="Kullanım Şartları" summary="Hesap, içerik, güvenlik, üçüncü taraf hizmetleri, yaptırım ve uyuşmazlık kurallarını açık ve dengeli biçimde belirler." sections={sections} notice="Bu metin genel bir taslaktır; işletme kimliği, satış modeli ve hedef kullanıcı kitlesi netleştiğinde Türkiye’de yetkili bir hukukçu tarafından üretim öncesinde doğrulanmalıdır." />;
}
